"""Chapter four: authored constraints, physical access puzzles and reproducible maps."""
from chapter4_layout import *
from itertools import permutations,product

def P(fr,en):return pair(fr,en)
def puzzle(l,k,cell,title,mode,rules,method,solution,actions,**kw):
    # Full rules are on the console too: returning to the journal is optional.
    return l.puzzle(k,cell,P(*title),P(*rules),mode,[P('Recoupez les deux notes du secteur et observez le résultat de vos manipulations.','Compare both sector notes and observe the effect of your changes.'),P(*method)],P(*solution),actions,**kw)
def notes(l,k,positions,texts):
    for i,(pos,t) in enumerate(zip(positions,texts)):
        l.clue('n'+str(2*k-1+i),pos,(k+1)*100+1+i,P('Consigne '+str((k+1)*100+1+i),'Instruction '+str((k+1)*100+1+i)),P(*t))
def observations(l,positions,texts):
    for i,(pos,t) in enumerate(zip(positions,texts)):
        l.clue('obs'+str(i),pos,210+i,P(['Registre local A','Registre local B','Registre local C'][i],['Local record A','Local record B','Local record C'][i]),P(*t))
    return [f'c{l.n}_obs{i}' for i in range(3)]
def options(pairs):return [tr(*p) for p in pairs]

l=Level(16,P('Bienvenue, vous habitez ici','Welcome, you live here'),'Une gare en éventail : trois guichets au nord, un hall commun, puis deux labyrinthes de maintenance au sud. Les badges commandent les trois guichets ; le sas 111 mène aux dossiers et le sas 112 aux tubes.',P('« Votre logement, votre emploi et vos opinions sont prêts. Votre arrivée, en revanche, n’a pas été autorisée. Veuillez démontrer votre présence. » — Folamour','“Your home, job and opinions are ready. Your arrival, however, was not authorised. Please demonstrate your presence.” — Folamour'),P('Le dossier retrouvé porte votre numéro de sujet : 16. Une demande de départ y figure déjà, refusée hier, avant votre arrivée. Votre permis provisoire impose une visite du quartier témoin.','The recovered file bears your subject number: 16. It already includes a departure request, refused yesterday, before you arrived. Your temporary permit requires an inspection of the model district.'))
l.layout_en='A fan-shaped station: three northern counters, a shared hall, then two southern maintenance mazes. Badges control the counters; gate 111 leads to records and gate 112 to tubes.'
l.rect(1,33,9,13)
for x in [7,17,27]:l.rect(x-2,x+2,1,5);l.rect(x,x,5,9)
l.maze(1,15,17,33);l.maze(19,33,17,33);l.rect(3,3,13,17);l.rect(15,19,29,29)
obs=observations(l,[(7,3),(17,3),(27,3)],[('A / Résident : le sujet 16 a une clé triangulaire. Aucune clé carrée ne lui appartient.','A / Resident: subject 16 has a triangular key. No square key belongs to them.'),('B / Technicien : le sujet 16 est arrivé par le quai C. Le lecteur garde la trace du badge, pas celle de la personne.','B / Technician: subject 16 arrived at platform C. The reader records the badge, not the person.'),('C / Inspecteur : le dossier valable a un tampon AJOURNÉ. Un dossier ANTICIPÉ décrit un événement qui n’a pas eu lieu.','C / Inspector: the valid file is stamped DEFERRED. An ANTICIPATED file describes an event that has not happened.')])
notes(l,1,[(1,11),(33,11)],[('Le terminal 203 change votre badge. Résident ouvre A ; technicien ouvre B ; inspecteur ouvre C. Un seul badge actif. Les autres portes se ferment.','Terminal 203 changes your badge. Resident opens A; technician opens B; inspector opens C. Only one badge is active. The other doors close.'),('Lire les trois registres 210, 211 et 212, puis revenir au 203 en inspecteur pour certifier la présence. Les changements se font uniquement près du terminal. Les registres lus restent dans le journal.','Read records 210, 211 and 212, then return to 203 as inspector to certify presence. Changes are made only near the terminal. Read records remain in the journal.')])
puzzle(l,1,(17,11),('Le droit d’exister','The right to exist'),'badges',('Installer la mallette. Changer de badge ici, visiter chaque guichet, puis revenir. Lire A en résident, B en technicien et C en inspecteur ; certifier avec le badge inspecteur.','Install the kit. Change badge here, visit each counter, then return. Read A as resident, B as technician and C as inspector; certify with the inspector badge.'),('Chaque badge donne un accès différent. Aucun ne suffit seul. Les trois lectures restent acquises quand vous changez de badge.','Each badge grants a different access. None suffices alone. All three readings remain recorded when you change badges.'),('Depuis 203 : résident → lire 210 → retour ; technicien → lire 211 → retour ; inspecteur → lire 212 → retour. Choisir inspecteur et valider.','From 203: resident → read 210 → return; technician → read 211 → return; inspector → read 212 → return. Select inspector and validate.'),[2],observations=obs,labels=options([('Résident','Resident'),('Technicien','Technician'),('Inspecteur','Inspector')]),world_gates=[dict(cell=[x,7],channel=0,allowed=[i],label='ABC'[i]) for i,x in enumerate([7,17,27])])
notes(l,2,[(1,17),(15,33)],[('Les trois registres du hall décrivent votre dossier : forme de clé, quai et tampon. Les cinq dossiers du pupitre sont complets. Un seul respecte les trois constats ensemble.','The three hall records describe your file: key shape, platform and stamp. The five console files are complete. Only one matches all three observations.'),('A : triangle / B / ajourné. B : carré / C / ajourné. C : triangle / C / anticipé. D : triangle / C / ajourné. E : carré / B / anticipé.','A: triangle / B / deferred. B: square / C / deferred. C: triangle / C / anticipated. D: triangle / C / deferred. E: square / B / anticipated.')])
puzzle(l,2,(7,23),('La personne qui n’est pas arrivée','The person who never arrived'),'records',('Choisir le dossier, puis associer les trois preuves physiques : clé, quai, tampon. Un dossier anticipé ne prouve pas une arrivée.','Choose the file, then attach the three physical facts: key, platform, stamp. An anticipated file does not prove an arrival.'),('Le registre A impose triangle, B impose quai C, C impose ajourné. D est le seul dossier qui combine les trois.','Record A requires triangle, B requires platform C, C requires deferred. D is the only file combining all three.'),('Dossier D ; clé triangle ; quai C ; tampon ajourné. Valider.','File D; triangular key; platform C; deferred stamp. Validate.'),[0,0,0,1,2,2,3],labels=options([('Dossier','File'),('Clé','Key'),('Quai','Platform'),('Tampon','Stamp')]),choices=[['A','B','C','D','E'],options([('Carré','Square'),('Triangle','Triangle')]),['A','B','C'],options([('Anticipé','Anticipated'),('Ajourné','Deferred')])],target=[3,1,2,1])
notes(l,3,[(19,17),(33,33)],[('Deux capsules partent de A puis D. Les aiguillages conservent le même réglage pendant les deux trajets. La capsule de A doit visiter B puis arriver à X. Celle de D doit visiter C puis arriver à Y.','Two capsules start at A then D. Switch settings stay fixed for both trips. The A capsule must visit B then reach X. The D capsule must visit C then reach Y.'),('Chaque aiguillage a deux sorties indiquées sur le schéma. Une boucle est refusée. Tester montre les deux trajets complets ; changer un réglage efface la certification du test.','Each switch has two outputs shown on the diagram. Loops are rejected. Testing displays both complete routes; changing a setting invalidates that test.')])
puzzle(l,3,(27,23),('Les tubes de régularisation','Regularisation tubes'),'tubes',('Régler A, B, C et D pour acheminer A → B → X et D → C → Y, avec les mêmes aiguillages. Le diagramme affiche les deux sorties possibles de chaque nœud. Tester puis valider.','Set A, B, C and D to route A → B → X and D → C → Y with unchanged switches. The diagram shows both possible outputs at every node. Test and validate.'),('Fixer d’abord les arrivées : B doit viser X et C doit viser Y. A rejoint B ; D rejoint C.','Set the destinations first: B points to X and C to Y. A connects to B; D connects to C.'),('A → B ; B → X ; C → Y ; D → C. Tester puis valider.','A → B; B → X; C → Y; D → C. Test and validate.'),[0,2,3,98],edges=[[2,1],[4,0],[1,5],[0,2]],names=['A','B','C','D','X','Y'],starts=[0,3],goals=[4,5],via=[1,2])
l.finish([17,13],[15,11],[19,13],[((1,13),P('Toute personne absente est priée de se présenter immédiatement.','All absent persons must report immediately.')),((15,17),P('Le logement de fonction est équipé d’une fenêtre donnant sur la prochaine fenêtre.','The assigned home includes a window overlooking the next window.')),((19,33),P('Votre recours a été accepté comme preuve de votre insatisfaction.','Your appeal was accepted as evidence of your dissatisfaction.'))],[([3,15],'y'),([17,29],'x')],[33,25])

l=Level(17,P('Le quartier témoin','The model district'),'Une rue verticale dessert trois maisons à horaires décalés, à l’ouest d’un jardin inaccessible. Deux quartiers labyrinthiques occupent le nord-est et le sud-est, reliés par une ruelle étroite.',P('« Ce quartier est notre plus belle réussite. Personne n’y a jamais été surpris. Nous comptons sur vous pour que cela continue. » — Folamour','“This district is our finest achievement. Nobody here has ever been surprised. We count on you to keep it that way.” — Folamour'),P('Ada avait raison : la rue est sèche à midi, malgré l’averse annoncée. Les autres habitants décrivent le bulletin, pas leur fenêtre. MIROIR signale maintenant Ada comme une défaillance du dispositif météorologique.','Ada was right: the street is dry at noon despite the forecast downpour. The other residents describe the bulletin, not their windows. MIRROR now reports Ada as a weather-system failure.'))
l.layout_en='A vertical street serves three houses on different schedules, west of an inaccessible garden. Two maze-like blocks stand northeast and southeast, linked by a narrow lane.'
l.maze(1,5,1,33);l.rect(7,7,1,33);l.rect(5,7,9,9);l.rect(5,7,25,25);l.rect(3,7,17,17)
for y in [5,17,29]:l.rect(11,15,y-2,y+2);l.rect(7,11,y,y)
l.rect(7,19,1,1);l.maze(19,33,1,15);l.maze(19,33,19,33);l.rect(31,31,15,19)
obs=observations(l,[(13,5),(13,17),(13,29)],[('MATIN / 08 h : le pluviomètre mécanique indique 0 mm. Le volet de la maison A est fermé. Le pain attend à la boulangerie.','MORNING / 08:00: the mechanical rain gauge reads 0 mm. House A has its shutter closed. Bread waits at the bakery.'),('MIDI / 12 h : le pluviomètre indique encore 0 mm. Ada observe une rue sèche. Le bulletin annonce pourtant une averse. Le volet A est ouvert.','NOON / 12:00: the rain gauge still reads 0 mm. Ada observes a dry street. The bulletin nevertheless announces a downpour. Shutter A is open.'),('SOIR / 18 h : le pluviomètre reste à 0 mm. Boris et Cyril répètent le bulletin de midi. La vitre réelle n’a aucune goutte.','EVENING / 18:00: the gauge remains at 0 mm. Boris and Cyril repeat the noon bulletin. The real window has no drops.')])
notes(l,1,[(1,1),(5,33)],[('Le pupitre 203 change toute la rue entre matin, midi et soir. Aucune horloge réelle. Maison A ouverte le matin, B à midi, C le soir. Les habitants et les volets suivent la phase choisie.','Console 203 switches the street between morning, noon and evening. No real-time clock. House A opens in the morning, B at noon, C in the evening. Residents and shutters follow the chosen phase.'),('Visiter 210, 211 et 212 dans leurs phases respectives. Après les trois observations, revenir à midi pour figer l’état contesté. Les constats restent dans le journal.','Visit 210, 211 and 212 in their respective phases. After all three observations, return to noon to freeze the disputed state. Records stay in the journal.')])
puzzle(l,1,(5,17),('Une journée parfaitement normale','A perfectly normal day'),'routine',('Installer la mallette, choisir une phase, puis visiter la maison accessible. Enregistrer matin, midi et soir. Revenir au pupitre et choisir midi avant de valider.','Install the kit, choose a phase, then visit the accessible house. Record morning, noon and evening. Return to the console and choose noon before validating.'),('Les portes changent avec la phase, les constats s’accumulent. Après les trois visites, midi est la phase de l’alerte.','Doors change with the phase; records accumulate. After all three visits, noon is the phase of the alert.'),('Matin → lire 210 → retour ; midi → lire 211 → retour ; soir → lire 212 → retour. Régler MIDI et valider.','Morning → read 210 → return; noon → read 211 → return; evening → read 212 → return. Set NOON and validate.'),[1],observations=obs,labels=options([('Matin','Morning'),('Midi','Noon'),('Soir','Evening')]),world_gates=[dict(cell=[9,y],channel=0,allowed=[i],label='ABC'[i]) for i,y in enumerate([5,17,29])])
notes(l,2,[(19,1),(33,15)],[('Quatre livraisons aux heures 8, 10, 12 et 14, une par créneau. Ada est livrée avant Boris. Cyril est livré immédiatement avant Daria.','Four deliveries at 8, 10, 12 and 14, one per slot. Ada is delivered before Boris. Cyril is delivered immediately before Daria.'),('Ada n’est pas livrée à 8 h. Boris n’est pas livré à 14 h. Les heures du bulletin sont sans valeur : utilisez les tickets des quatre livraisons.','Ada is not delivered at 8. Boris is not delivered at 14. Bulletin times have no value: use the four delivery tickets.')])
# These clues force C,D,A,B? A cannot8 B cannot14 -> check then select useful unique constraints below.
# A at10 B12, C/D cannot adjacent remaining 8/14: no solution. Replace Boris condition with Daria not14.
for e in l.E:
 if e['id']=='c17_n4':
  e['text']=tr('Ada n’est pas livrée à 8 h. Daria n’est pas livrée à 14 h. Utilisez les tickets physiques, pas les heures du bulletin.','Ada is not delivered at 8. Daria is not delivered at 14. Use physical tickets, not bulletin times.')
puzzle(l,2,(25,7),('Le facteur qui livre hier','The postman delivering yesterday'),'timetable',('Une livraison à 8, 10, 12 et 14 h. Ada avant Boris ; Cyril immédiatement avant Daria ; Ada pas à 8 h ; Daria pas à 14 h. Une seule personne par heure.','One delivery at 8, 10, 12 and 14. Ada before Boris; Cyril immediately before Daria; Ada not at 8; Daria not at 14. One person per slot.'),('Le duo Cyril-Daria ne peut occuper 12-14. S’il occupait 10-12, Ada serait forcée à 8. Donc Cyril 8, Daria 10, Ada 12, Boris 14.','Cyril-Daria cannot occupy 12-14. At 10-12, Ada would be forced to 8. Therefore Cyril 8, Daria 10, Ada 12, Boris 14.'),('Ada 12 ; Boris 14 ; Cyril 8 ; Daria 10. Valider.','Ada 12; Boris 14; Cyril 8; Daria 10. Validate.'),[0,0,1,1,1,3],labels=['Ada','Boris','Cyril','Daria'],choices=[['08:00','10:00','12:00','14:00']]*4,target=[2,3,0,1])
notes(l,3,[(19,19),(33,33)],[('Ada : « La rue est sèche à midi. » Boris : « Averse confirmée par la radio. » Cyril : « Averse confirmée par Boris. » Daria : « Le volet A reste fermé toute la journée. »','Ada: “The street is dry at noon.” Boris: “Downpour confirmed by radio.” Cyril: “Downpour confirmed by Boris.” Daria: “Shutter A stays closed all day.”'),('Une observation fiable doit correspondre aux trois relevés et provenir d’un constat direct. La radio diffuse MIROIR. Choisir le témoin et les deux instruments indépendants, pas les copies.','A reliable observation must match all three records and come from direct observation. The radio broadcasts MIRROR. Choose the witness and the two independent instruments, not copies.')])
puzzle(l,3,(27,25),('L’anomalie est dans le bulletin','The anomaly is in the bulletin'),'anomaly',('Choisir le témoin fiable. Joindre exactement deux preuves indépendantes parmi pluviomètre, radio, vitre réelle et rapport de Boris.','Choose the reliable witness. Attach exactly two independent proofs from rain gauge, radio, real window and Boris’s report.'),('Ada voit directement la rue. Le pluviomètre et la vitre vérifient son constat sans dépendre de MIROIR.','Ada sees the street directly. The rain gauge and window verify her observation independently of MIRROR.'),('Ada ; conserver pluviomètre et vitre réelle ; écarter radio et rapport de Boris. Valider.','Ada; keep rain gauge and real window; exclude radio and Boris’s report. Validate.'),[1,3],labels=options([('Témoin','Witness'),('Pluviomètre','Rain gauge'),('Radio','Radio'),('Vitre réelle','Real window'),('Rapport de Boris','Boris’s report')]),choices=[['Ada','Boris','Cyril','Daria']]+[options([('Écarter','Exclude'),('Conserver','Keep')])]*4,target=[0,1,0,1,0])
l.finish([7,33],[7,31],[7,27],[((1,33),P('Le bonheur est obligatoire. Toute amélioration sera considérée comme une critique.','Happiness is compulsory. Any improvement will be treated as criticism.')),((33,1),P('Le facteur a livré demain. Sa ponctualité fait l’objet d’une enquête.','The postman delivered tomorrow. His punctuality is under investigation.')),((19,33),P('Le jardin est interdit aux plantes non prévues au plan.','Plants absent from the plan are forbidden in the garden.'))],[([17,1],'x'),([31,17],'y')],[33,23])

l=Level(18,P('Le ministère des regards','The ministry of gazes'),'Deux anneaux de surveillance entourent une tour centrale. Depuis l’anneau extérieur, trois niches à l’est se ferment selon les caméras. Un pont ouest mène aux montages ; une entrée nord mène aux sources.',P('« Pour obtenir votre certificat de discrétion, veuillez réparer les appareils qui vous regardent. Ils sont momentanément occupés à s’observer entre eux. » — Folamour','“To obtain your discretion certificate, repair the devices watching you. They are currently busy observing one another.” — Folamour'),P('Les trois alertes prétendument indépendantes remontent toutes au même bulletin. Le film original montre un chariot de nettoyage. MIROIR en avait déduit une invasion, puis demandé une confirmation à sa propre copie.','All three supposedly independent alerts trace back to one bulletin. The original film shows a cleaning cart. MIRROR inferred an invasion, then asked its own copy to confirm it.'))
l.layout_en='Two surveillance rings surround a central tower. Three eastern niches off the outer ring close according to camera settings. A western bridge leads to editing; a northern entry leads to sources.'
l.rect(1,33,1,33);l.rect(6,28,6,28,0);l.rect(9,25,9,25);l.rect(13,21,13,21,0);l.rect(15,19,15,19);l.rect(5,9,17,17);l.rect(17,17,9,15)
# Break large open rings into corridors and alcoves without changing the two choke points.
for a,b,c,d in [(2,4,9,13),(2,4,21,25),(10,12,12,14),(22,24,20,22),(9,13,2,4),(21,25,30,32)]:l.rect(a,b,c,d,0)
for y in [7,17,27]:l.rect(27,29,y,y)
obs=observations(l,[(27,7),(27,17),(27,27)],[('A / La caméra archive le chariot à 09:10. Il transporte un balai. Aucun autre véhicule n’est visible.','A / The camera records the cart at 09:10. It carries a broom. No other vehicle is visible.'),('B / Le poste B déclenche un verrou lorsqu’il regarde vers l’ouest. Son image montre une copie de l’écran A, pas une deuxième caméra.','B / Station B locks when it looks west. Its image shows a copy of screen A, not a second camera.'),('C / La transmission mécanique confirme le passage du même chariot. La signature de MIROIR est ajoutée après la copie.','C / The mechanical transmission confirms the same cart’s passage. MIRROR’s signature is added after copying.')])
notes(l,1,[(1,1),(33,33)],[('A ouvre la niche A en regardant EST. B ferme la niche B en regardant OUEST : toute autre direction la libère. C ouvre la niche C en regardant NORD.','A opens niche A when looking EAST. B closes niche B when looking WEST: any other direction releases it. C opens niche C when looking NORTH.'),('Lire les trois registres 210-212 puis laisser les trois accès ouverts. Le panneau montre les orientations et l’état réel des portes. Les réglages se font au poste 203 seulement.','Read all three records 210-212, then leave all three accesses open. The panel shows orientations and actual gate states. Settings change only at station 203.')])
puzzle(l,1,(31,17),('Voir pour ouvrir, détourner pour passer','Look to open, look away to pass'),'gaze',('Installer la mallette. A vers EST ouvre A ; B vers OUEST ferme B ; C vers NORD ouvre C. Régler les caméras, lire les trois niches physiques, puis valider avec tous les accès ouverts.','Install the kit. A EAST opens A; B WEST closes B; C NORTH opens C. Set the cameras, read the three physical niches, then validate with all accesses open.'),('La caméra B inverse la règle : il faut détourner son regard. Les directions nord, est et sud sont toutes valables pour B.','Camera B reverses the rule: look away. North, east and south all work for B.'),('A EST ; B SUD (ou NORD/EST) ; C NORD. Visiter 210, 211 et 212. Retour au 203, tester puis valider.','A EAST; B SOUTH (or NORTH/EAST); C NORTH. Visit 210, 211 and 212. Return to 203, test and validate.'),[0,1,1,98],observations=obs,world_gates=[dict(cell=[28,y],channel=i,allowed=allowed,label='ABC'[i]) for i,(y,allowed) in enumerate(zip([7,17,27],[[1],[0,1,2],[0]]))])
notes(l,2,[(9,9),(25,25)],[('Chaque fragment montre le début et la fin d’une action. Relier la fin d’un fragment au début du suivant. Commencer PORTE FERMÉE, finir RUE VIDE. Utiliser chaque fragment une seule fois.','Each fragment shows an action’s start and end. Join each fragment’s end to the next start. Begin CLOSED DOOR, end EMPTY STREET. Use each fragment exactly once.'),('A : chariot → balai. B : porte fermée → porte ouverte. C : balai → chariot. D : porte ouverte → chariot. E : chariot → rue vide. Sortir trop tôt par E abandonne le nettoyage.','A: cart → broom. B: closed door → open door. C: broom → cart. D: open door → cart. E: cart → empty street. Leaving early through E skips the cleaning.')])
puzzle(l,2,(11,17),('Le film coupé trop court','The film cut too short'),'splice',('Assembler les cinq fragments en raccordant leurs états. Départ porte fermée, fin rue vide. Chaque fragment une fois. Tester montre les raccords, y compris un éventuel retour au chariot.','Assemble all five fragments by matching states. Start closed door, finish empty street. Each fragment once. Testing shows the joins, including a possible return to the cart.'),('B ouvre la porte, D fait entrer le chariot. Le détour A-C explique le nettoyage. E termine le film.','B opens the door, D brings in the cart. The A-C detour explains the cleaning. E ends the film.'),('B → D → A → C → E. Tester puis valider.','B → D → A → C → E. Test and validate.'),[1,3,0,2,4,98],cards=options([('A · Chariot → balai','A · Cart → broom'),('B · Porte fermée → ouverte','B · Closed → open door'),('C · Balai → chariot','C · Broom → cart'),('D · Porte ouverte → chariot','D · Open door → cart'),('E · Chariot → rue vide','E · Cart → empty street')]),joins=[[2,3],[0,1],[3,2],[1,2],[2,4]],max_commands=5)
notes(l,3,[(15,15),(19,19)],[('R1 cite R2. R2 cite R3. R3 cite MIROIR. R4 vient du capteur mécanique. R5 copie R4. Une copie conserve l’origine et ne crée jamais une mesure indépendante.','R1 cites R2. R2 cites R3. R3 cites MIRROR. R4 comes from the mechanical sensor. R5 copies R4. A copy retains its origin and never creates an independent measurement.'),('Attribuer à R1-R5 leur origine ultime. Puis annoncer combien de familles de mesures physiques indépendantes figurent dans ces cinq rapports. Une famille copiée compte une seule fois.','Assign the ultimate origin of R1-R5. Then report how many independent physical measurement families appear in these reports. A copied family counts only once.')])
puzzle(l,3,(15,17),('Une rumeur en cinq exemplaires','A rumour in five copies'),'origins',('Remonter R1 → R2 → R3 → MIROIR et R5 → R4 → capteur. Classer chaque origine ultime et compter les familles physiques indépendantes.','Trace R1 → R2 → R3 → MIRROR and R5 → R4 → sensor. Classify ultimate origins and count independent physical families.'),('R1, R2 et R3 sont issus de MIROIR. R4 et R5 sont une seule famille mécanique. Le nombre de signatures ne compte pas.','R1, R2 and R3 come from MIRROR. R4 and R5 form one mechanical family. Signature count is irrelevant.'),('R1-R3 : MIROIR ; R4-R5 : capteur ; familles physiques : 1. Valider.','R1-R3: MIRROR; R4-R5: sensor; physical families: 1. Validate.'),[3,4,5],labels=['R1','R2','R3','R4','R5',tr('Familles physiques','Physical families')],choices=[['MIROIR',tr('Capteur','Sensor')]]*5+[['0','1','2','3','4','5']],target=[0,0,0,1,1,1])
l.finish([3,31],[1,31],[5,31],[((1,33),P('Pour votre intimité, cette caméra est équipée d’un rideau dessiné.','For your privacy, this camera includes a painted curtain.')),((25,9),P('Le service des angles morts refuse de communiquer son adresse.','The blind-spot department refuses to disclose its address.')),((19,15),P('Une caméra surveille le voyant indiquant qu’elle ne surveille personne.','A camera watches the indicator stating it watches nobody.'))],[([7,17],'x'),([17,13],'y')],[17,19])

l=Level(19,P('La fabrique du lendemain','The tomorrow factory'),'Trois chaînes en tresses traversent le complexe : énergie à l’ouest, convoyeurs au centre, assemblage à l’est. Les passerelles changent de hauteur sur le plan ; les ateliers latéraux forment des boucles de retour.',P('« Nous produisons aujourd’hui les solutions aux problèmes que nous annoncerons demain. Votre ascenseur est une commande mineure. Essayez de ne pas déranger les grandes. » — Folamour','“Today we produce solutions to problems we will announce tomorrow. Your lift is a minor order. Try not to disturb the major ones.” — Folamour'),P('L’ascenseur est réparé. Derrière sa pièce minuscule, les chaînes poursuivent des coques effilées, des systèmes de guidage et des capsules de tranquillité. La commande porte la mention HORIZON. Il manque seulement l’accord du directoire.','The lift is repaired. Behind its tiny part, the lines keep producing tapered shells, guidance systems and tranquillity capsules. The order is marked HORIZON. Only the directorate’s approval is missing.'))
l.layout_en='Three braided production lines cross the complex: power west, conveyors centre, assembly east. Walkways change position across the plan; side workshops form return loops.'
for a,b in [(1,11),(15,23),(27,33)]:l.maze(a,b,1,33)
l.rect(11,15,27,27);l.rect(23,27,7,7)
for a,b,y in [(3,9,7),(17,21,17),(29,31,27)]:l.rect(a,b,y,y+2)
notes(l,1,[(1,1),(11,33)],[('Trois générateurs A, B, C distribuent six unités au total. La presse reçoit A+B et demande 5. Le refroidissement reçoit B+C et demande 4. Le guidage reçoit A+C et demande 3.','Generators A, B and C distribute six units total. The press receives A+B and needs 5. Cooling receives B+C and needs 4. Guidance receives A+C and needs 3.'),('Une unité de générateur alimente deux postes par les circuits existants. Il ne faut pas additionner les besoins comme s’ils étaient indépendants. Les jauges affichent chaque somme.','Each generator unit feeds two stations through existing circuits. Do not add demands as if independent. Gauges display every sum.')])
puzzle(l,1,(5,9),('L’énergie compte deux fois','Power counts twice'),'energy',('Répartir six unités entre A, B et C. Atteindre simultanément A+B=5, B+C=4 et A+C=3. Les jauges réagissent immédiatement.','Distribute six units among A, B and C. Simultaneously reach A+B=5, B+C=4 and A+C=3. Gauges respond immediately.'),('Comparer les sommes : A est une unité plus grand que C ; B est deux unités plus grand que C. Avec six unités, C=1, A=2, B=3.','Compare sums: A is one greater than C; B is two greater than C. With six units, C=1, A=2, B=3.'),('A=2 ; B=3 ; C=1. Valider.','A=2; B=3; C=1. Validate.'),[0,0,1,1,1,2],budget=6)
notes(l,2,[(15,1),(23,33)],[('Le convoyeur part de D. À chaque case numérotée, l’aiguillage choisit sa sortie 0 ou 1. La pièce doit être moulée M, refroidie R, puis contrôlée C avant la sortie S.','The conveyor starts at D. Each numbered switch chooses output 0 or 1. The part must be moulded M, cooled R, then checked C before exit S.'),('Un passage à C avant R échoue ; R avant M échoue. La pièce peut repasser par un aiguillage, mais un circuit qui répète exactement le même état est une boucle. Les pièces d’essai sont toujours récupérées.','Passing C before R fails; R before M fails. A part may revisit a switch, but repeating the exact same state is a loop. Test parts are always recovered.')])
puzzle(l,2,(19,19),('La pièce qui repasse','The returning part'),'conveyor',('Régler les trois aiguillages. Le trajet doit visiter M → R → C → S. Les sorties possibles et les stations apparaissent sur le schéma. Tester fournit une trace et la cause d’un refus.','Set the three switches. The route must visit M → R → C → S. Possible outputs and stations appear on the diagram. Testing gives a trace and any rejection cause.'),('Le premier aiguillage doit entrer dans M. Le deuxième doit envoyer vers R. Le dernier rejoint C, qui mène à S. Les autres sorties recirculent ou sautent une opération.','The first switch must enter M. The second sends to R. The last joins C, leading to S. Other outputs recirculate or skip an operation.'),('Aiguillages 1=1 ; 2=0 ; 3=1. Tester : D → 1 → M → 2 → R → 3 → C → S. Valider.','Switches 1=1; 2=0; 3=1. Test: D → 1 → M → 2 → R → 3 → C → S. Validate.'),[0,2,98],edges=[[2,3],[4,0],[1,5]],names=['1','2','3','M','R','C','S'],fixed={'3':1,'4':2,'5':6},stations={'3':0,'4':1,'5':2})
notes(l,3,[(27,1),(33,33)],[('Monter le socle avant le moteur et le guide. Le moteur doit précéder la courroie. Le guide doit précéder le capot. La courroie doit précéder le capot. Le contrôle clôt l’assemblage.','Fit the base before the motor and guide. Motor before belt. Guide before cover. Belt before cover. Inspection completes assembly.'),('Le moteur et le guide peuvent être montés dans les deux ordres. Aucun ordre arbitraire n’est imposé si toutes les dépendances sont respectées. Tester indique la première dépendance manquante.','Motor and guide can be fitted in either order. No arbitrary order is imposed when all dependencies are met. Testing identifies the first missing dependency.')])
puzzle(l,3,(29,27),('Une petite pièce dans une grande machine','A small part in a big machine'),'assembly',('Programmer les six opérations selon les dépendances : socle avant moteur/guide ; moteur avant courroie ; guide et courroie avant capot ; capot avant contrôle. Tester puis valider.','Program six operations: base before motor/guide; motor before belt; guide and belt before cover; cover before inspection. Test and validate.'),('Le socle est premier, le contrôle dernier. Entre les deux, conserver les liens de dépendance ; plusieurs ordres intermédiaires sont acceptés.','Base comes first, inspection last. Preserve dependencies between them; multiple intermediate orders are accepted.'),('Socle → moteur → guide → courroie → capot → contrôle. Tester puis valider. Guide et moteur peuvent être inversés.','Base → motor → guide → belt → cover → inspection. Test and validate. Guide and motor may be swapped.'),[0,1,2,3,4,5,98],cards=options([('Socle','Base'),('Moteur','Motor'),('Guide','Guide'),('Courroie','Belt'),('Capot','Cover'),('Contrôle','Inspection')]),dependencies=[[],[0],[0],[1],[2,3],[4]],max_commands=6)
l.finish([1,33],[3,33],[1,31],[((11,1),P('Commande : 1 pièce d’ascenseur. Emballage : 400 tonnes de matériel préventif.','Order: one lift part. Packaging: 400 tons of preventive equipment.')),((23,1),P('Les capsules de tranquillité ne doivent jamais être secouées par le doute.','Tranquillity capsules must never be shaken by doubt.')),((27,33),P('Objectif de production : suffisamment. Nouveau quota : davantage.','Production target: enough. New quota: more.'))],[([13,27],'x'),([25,7],'x')],[33,19])

l=Level(20,P('L’unanimité absolue','Absolute unanimity'),'Une salle de décision centrale dessert cinq bureaux : un au nord, deux à l’ouest et deux à l’est. Les couloirs latéraux contournent les bureaux, tandis que les deux sas gardent les réseaux du conseil.',P('« Nous sommes tous d’accord. Nous attendons simplement de savoir avec qui. » Cinq Folamour occupent cinq bureaux. Chaque signature attend les quatre autres.','“We all agree. We are simply waiting to learn with whom.” Five Folamours occupy five offices. Each signature waits for the other four.'),P('Vous avez remplacé les copies par des constats et réuni les signatures. MIROIR annonce : « CERTITUDE INSUFFISANTE. » Folamour ouvre un tiroir : « Toute incertitude déclenche le protocole de sérénité maximale. C’est écrit très petit, mais très officiellement. » L’ascenseur monte vers un hangar vertical. Des silhouettes de fusées disparaissent dans l’obscurité. PROGRAMME HORIZON — POUR QUE PLUS JAMAIS RIEN NE PUISSE ARRIVER. « Ah, vous voilà. Nous cherchions quelqu’un pour la vérification finale. » CHAPITRE 5 À VENIR.','You replaced copies with observations and collected the signatures. MIRROR announces: “INSUFFICIENT CERTAINTY.” Folamour opens a drawer: “Any uncertainty triggers the maximum serenity protocol. Tiny print, very official.” The lift rises into a vertical hangar. Rocket silhouettes disappear into darkness. HORIZON PROGRAMME — SO NOTHING CAN EVER HAPPEN AGAIN. “Ah, there you are. We needed someone for the final check.” CHAPTER 5 TO COME.'))
l.layout_en='A central decision room serves five offices: one north, two west and two east. Side corridors go around offices while two gates guard the council networks.'
l.rect(13,21,13,21);l.maze(13,21,1,9);l.rect(17,17,9,13)
for a,b in [(1,9),(25,33)]:
 l.maze(a,b,1,11);l.maze(a,b,23,33);l.rect(a+4,a+4,11,23)
l.rect(5,13,17,17);l.rect(21,29,17,17)
notes(l,1,[(13,1),(21,9)],[('Cinq bureaux : habitat, météo, sécurité, industrie, transport. Affecter à chacun une preuve originale. Le dossier d’arrivée ne va ni à la météo ni à l’industrie. Le pluviomètre va au service qui annonce le temps.','Five offices: housing, weather, security, industry, transport. Assign one original proof to each. The arrival file belongs to neither weather nor industry. The rain gauge belongs to the weather office.'),('Le film du chariot va à la sécurité. Le bon des coques va à l’industrie. Le test de l’ascenseur va au transport. Chaque preuve et chaque bureau sont utilisés une fois.','The cart film belongs to security. The shell order belongs to industry. The lift test belongs to transport. Use every proof and office once.')])
puzzle(l,1,(17,17),('Cinq faits contre cinq certitudes','Five facts against five certainties'),'exhibits',('Affecter une preuve à chaque bureau, sans doublon. Les copies ont été retirées ; les cinq originaux sont disponibles, même lors d’un accès direct à ce niveau.','Assign one proof to each office without duplicates. Copies have been removed; all five originals are available even when starting this level directly.'),('Sécurité reçoit film, industrie reçoit commande, transport reçoit ascenseur, météo reçoit pluviomètre. Le dossier d’arrivée reste pour habitat.','Security gets film, industry gets order, transport gets lift, weather gets rain gauge. The arrival file remains for housing.'),('Habitat : dossier ; météo : pluviomètre ; sécurité : film ; industrie : commande ; transport : ascenseur. Valider.','Housing: file; weather: rain gauge; security: film; industry: order; transport: lift. Validate.'),[0,0,1,1,1,1,3,4,4,4],labels=options([('Habitat','Housing'),('Météo','Weather'),('Sécurité','Security'),('Industrie','Industry'),('Transport','Transport')]),choices=[options([('Film','Film'),('Commande','Order'),('Dossier','File'),('Ascenseur','Lift'),('Pluviomètre','Rain gauge')])]*5,target=[2,4,0,1,3])
notes(l,2,[(1,1),(9,33)],[('A peut croire B ou le capteur X. B peut croire C ou A. C peut croire A ou le capteur Y. D peut croire E ou B. E peut croire D ou C. X et Y sont les seuls constats physiques.','A may trust B or sensor X. B may trust C or A. C may trust A or sensor Y. D may trust E or B. E may trust D or C. X and Y are the only physical observations.'),('A et B doivent finir sur X ; C, D et E doivent finir sur Y. Aucune boucle n’est recevable. Une chaîne de copies aboutissant au bon capteur est recevable, mais ne multiplie pas les preuves.','A and B must terminate at X; C, D and E at Y. No loop is admissible. A copy chain ending at the right sensor is admissible but does not multiply evidence.')])
puzzle(l,2,(5,17),('Le réseau de confiance','The trust network'),'trust',('Choisir une source pour chaque bureau. A et B doivent remonter à X ; C, D et E à Y. Tester trace toutes les chaînes et signale les boucles.','Choose each office’s source. A and B must trace to X; C, D and E to Y. Testing traces every chain and reports loops.'),('A doit joindre X, B doit joindre A, C doit joindre Y. D ne peut passer par B (origine X) : il rejoint E, qui rejoint C.','A must join X, B must join A, C must join Y. D cannot use B (origin X): it joins E, which joins C.'),('A → X ; B → A ; C → Y ; D → E ; E → C. Tester puis valider.','A → X; B → A; C → Y; D → E; E → C. Test and validate.'),[0,1,2,4,98],edges=[[1,5],[2,0],[0,6],[4,1],[3,2]],names=['A','B','C','D','E','X','Y'],goals=[5,5,6,6,6])
notes(l,3,[(25,1),(33,33)],[('Quatre copies portent leurs dossiers au cinquième Folamour par une passerelle. Durées : A=1, B=2, C=5, D=8 unités. Au plus deux copies traversent ensemble. Le sceau unique doit accompagner chaque traversée et chaque retour.','Four copies carry files to the fifth Folamour across a walkway. Durations: A=1, B=2, C=5, D=8 units. At most two copies cross together. The single seal accompanies every outward and return crossing.'),('Une traversée coûte la durée du plus lent. Tout le monde part côté bureaux. Amener les quatre copies et le sceau au conseil en 15 unités maximum. Le temps avance uniquement quand vous appuyez sur Traverser. Annuler restitue le temps.','A crossing costs the slower traveller’s duration. Everyone starts on the office side. Bring all four copies and the seal to the council within 15 units. Time advances only when pressing Cross. Undo restores time.')])
puzzle(l,3,(29,17),('Le sceau à usage collectif','The shared seal'),'seal',('Sélectionner une ou deux copies du côté du sceau, puis Traverser. Coût = durée du plus lent : A1, B2, C5, D8. Tous au conseil en 15 unités maximum. Aucune limite en temps réel. Annulation et remise à zéro disponibles.','Select one or two copies on the seal’s side, then Cross. Cost = slower duration: A1, B2, C5, D8. Everyone must reach the council in at most 15 units. No real-time limit. Undo and reset are available.'),('Faire voyager C et D ensemble économise leurs longs trajets. A et B servent de passeurs du sceau. Le plus rapide ne doit pas faire tous les retours.','Send C and D together to combine their long crossings. A and B shuttle the seal. The fastest should not make every return.'),('A+B aller (2), A retour (1), C+D aller (8), B retour (2), A+B aller (2). Total 15. Valider.','A+B across (2), A returns (1), C+D across (8), B returns (2), A+B across (2). Total 15. Validate.'),[0,1,98,0,98,2,3,98,1,98,0,1,98],times=[1,2,5,8],budget=15)
l.finish([17,21],[15,21],[19,21],[((21,1),P('Folamour original : « Les quatre autres sont des copies. » Exemplaire 5 sur 5.','Original Folamour: “The other four are copies.” Copy 5 of 5.')),((1,33),P('Le conseil a voté l’interdiction des votes divisés. Résultat : cinq versions différentes du procès-verbal.','The council banned divided votes. Result: five different minutes.')),((33,1),P('Programme HORIZON. Destination : suffisamment loin. Retour : non prévu au formulaire.','HORIZON programme. Destination: far enough. Return: absent from the form.'))],[([11,17],'x'),([23,17],'x')],[17,3])

# Persist metadata and bilingual additions. Dynamic visits get an executable route:
# walk to console, change setting, visit niche, return. No teleports in tests.
for n in range(16,21):
 E=json.loads((D/f'events{n}.json').read_text());by={e['id']:e for e in E};m=json.loads((D/f'maze{n}.json').read_text());F={(x,y) for y,row in enumerate(m['grid']) for x,v in enumerate(row) if v}
 p1=by[f'c{n}_p1'];route=json.loads((T/f'route_level{n}.json').read_text())
 if p1.get('world_gates'):
  # Recompute a physically legal route, inserting the three field visits just before p1.
  regular=[s['id'] for s in route if '_obs' not in s['id']];current=tuple(m['start']);done=set();new=[];settings=[0,0,0];collected=False
  def walk_to(id,actions=None):
   global current
   e=by[id];closed={tuple(e['cell']) for e in E if e['kind'] in ['door','exit'] and e['id'] not in done}
   if p1['id'] not in done:
    closed|={tuple(b['cell']) for b in p1['world_gates'] if settings[b['channel']] not in b['allowed']}
   targets=set(neighbours(tuple(e['cell']))) if e['kind']=='exit' else {tuple(e['cell'])}
   p=path(current,targets,F-closed);assert p,(n,id,current,settings)
   s=dict(id=id,route=p)
   if actions is not None:s['configure']=actions
   new.append(s);current=p[-1]
   if actions is None:done.add(id);done.update(e.get('opens',[]))
  for id in regular:
   if id==p1['id']:
    for i in range(3):
     acts=[i] if n in [16,17] else ([0] if i==0 else [])
     walk_to(id,acts)
     if n in [16,17]:settings[0]=i
     elif i==0:settings[0]=1
     walk_to(f'c{n}_obs{i}')
    walk_to(id,[])
   walk_to(id)
  route=new;save(T/f'route_level{n}.json',route)
 # Ensure all new complete titles/journal concatenations can localize.
 for e in E:
  en[e['title']+'\n'+e['text']]=en.get(e['title'],e['title'])+'\n'+en.get(e['text'],e['text'])
# static console strings
for fr,eng in [
 ('VERSION 0.18 · LE COMPLEXE DE LA CERTITUDE','VERSION 0.18 · THE CERTAINTY COMPLEX'),('Chapitre 4 — Le complexe de la certitude','Chapter 4 — The certainty complex'),('Reprendre le chapitre 4','Resume chapter 4'),('Entrer dans le complexe de la certitude','Enter the certainty complex'),('CHAPITRE 4 / LE COMPLEXE DE LA CERTITUDE','CHAPTER 4 / THE CERTAINTY COMPLEX'),('CHAPITRE 4 / MISSION TERMINÉE','CHAPTER 4 / ASSIGNMENT COMPLETE'),('CHAPITRE 4 TERMINÉ','CHAPTER 4 COMPLETE'),('Le chapitre 5 n’est pas encore jouable. Votre bilan est sauvegardé.','Chapter 5 is not playable yet. Your results are saved.'),('C4 / MISSION %d','C4 / ASSIGNMENT %d'),('Modifier ces accès exige de revenir au pupitre.','Return to the console to change these accesses.'),('Registres consultés : %d / 3','Records read: %d / 3'),('Réglage','Setting'),('OUVERT','OPEN'),('FERMÉ','CLOSED'),('Tester les trajets','Test routes'),('Boucle détectée','Loop detected'),('Opération hors ordre','Operation out of order'),('Trajet interrompu','Route interrupted'),('Dépendance manquante','Missing dependency'),('Raccord impossible','Join mismatch'),('Temps utilisé : %d / %d','Time used: %d / %d'),('Côté bureaux','Office side'),('Côté conseil','Council side'),('Sceau : %s','Seal: %s'),('Traverser','Cross'),('Annuler la traversée','Undo crossing'),('Sélectionner une ou deux copies du côté du sceau.','Select one or two copies on the seal’s side.'),('Budget dépassé : annuler une traversée ou réinitialiser.','Budget exceeded: undo a crossing or reset.'),('Presse : %d / 5','Press: %d / 5'),('Refroidissement : %d / 4','Cooling: %d / 4'),('Guidage : %d / 3','Guidance: %d / 3'),('Essai non conforme : vérifier les règles, les lectures physiques et le dernier test.','Trial not compliant: check rules, physical readings and latest test.'),('Réseau : sorties 0 / 1','Network: outputs 0 / 1'),('BUREAUX','OFFICES'),('CONSEIL','COUNCIL'),('Porte %s : %s','Gate %s: %s')]:tr(fr,eng)
save(D/'chapter4.json',design);save(R/'scripts/chapter4_design.json',design);save(T/'chapter4_solutions.json',{n:d['sections'] for n,d in design.items()});save(D/'en.json',en);save(D/'guidance.json',aid)
