"""HORIZON: authored finale, bilingual clues, reproducible geometry and routes."""
from chapter4_layout import *
from itertools import product, permutations

P = pair
def opts(values): return [tr(*v) for v in values]
def clicks(target): return [i for i,n in enumerate(target) for _ in range(n)]

class FinaleLevel(Level):
 def __init__(self,n,title,layout,intro,outro):
  super().__init__(n,title,layout[0],intro,outro)
  self.layout_en=layout[1];self.rng=random.Random(19000+n)
 def puzzle(self,k,cell,title,mode,rules,method,solution,actions,**kw):
  e=super().puzzle(k,cell,title,rules,mode,[P('Lisez les deux consignes du secteur. Les règles complètes figurent aussi sur ce poste.','Read both sector instructions. This station also contains all rules.'),method],solution,actions,**kw)
  e['puzzle_type']=e['model']='finale';return e
 def notes(self,k,positions,texts):
  for i,(pos,txt) in enumerate(zip(positions,texts)):
   self.clue('n'+str(2*k-1+i),pos,(k+1)*100+1+i,P('Consigne '+str((k+1)*100+1+i),'Instruction '+str((k+1)*100+1+i)),txt)

# 21: a long gantry spine, three inspection bays and two distinct service wings.
l=FinaleLevel(21,P('Le département des petites précautions','The department of minor precautions'),P('Une épine de maintenance longe trois baies de silos. Les ponts A/B/C donnent accès aux inspections. Le sas 111 conduit à la comptabilité au nord-est, le sas 112 au retour des capsules au sud-est.','A maintenance spine runs beside three silo bays. Bridges A/B/C lead to inspections. Gate 111 leads to accounting in the northeast; gate 112 to capsule returns in the southeast.'),P('HORIZON. Derrière les silhouettes aperçues au conseil, des fusées occupent des hangars entiers. PATIENCE. TENDRESSE. MODÉRATION. « Trois petites précautions. Nous avions prévu davantage de modération, mais le plafond était trop bas. » Le bon de fabrication porte le numéro de votre dernière validation.','HORIZON. Behind the silhouettes glimpsed at the council, rockets occupy entire hangars. PATIENCE. TENDERNESS. MODERATION. “Three minor precautions. We planned more moderation, but the ceiling was too low.” The manufacturing order bears your last approval number.'),P('Le registre distingue deux listes : les habitants conformes, à conserver sous terre ; les « variables extérieures », à traiter par HORIZON. Les pièces que vous avez validées alimentaient cette entreprise. Une ligne a été barrée au crayon : RETOUR. Vous rétablissez au moins celui des capsules d’essai.','The ledger separates compliant residents, to be kept underground, from “outside variables”, to be handled by HORIZON. The parts you approved served this enterprise. One line was crossed out in pencil: RETURN. You have restored it for the test capsules, at least.'))
l.maze(1,9,1,33);l.rect(11,11,1,33)
for y in [1,17,33]:l.rect(9,11,y,y)
for y in [5,17,29]:l.rect(15,19,y-2,y+2);l.rect(11,15,y,y)
l.maze(23,33,1,15);l.maze(23,33,19,33);l.rect(19,23,5,5);l.rect(29,29,15,19)
obs=[]
for i,y in enumerate([5,17,29]):
 e=l.clue('obs'+str(i),(17,y),210+i,P('Inspection '+ 'ABC'[i],'Inspection '+ 'ABC'[i]),[P('PATIENCE : capacité de cinq caisses-unités. Le dossier de poids 3 lui est affecté. Aucun équipement réel ne figure sur ce manifeste : seulement des formulaires.','PATIENCE: capacity five crate-units. The weight-3 file is assigned here. This manifest contains paperwork only.'),P('TENDRESSE : capacité cinq. La caisse de poids 1 accompagne celle de poids 4. Les caisses ne peuvent être divisées.','TENDERNESS: capacity five. The weight-1 crate accompanies weight 4. Crates cannot be split.'),P('MODÉRATION : capacité six. Le dossier de poids 6 voyage seul. Le coût du formulaire dépasse celui de son contenu.','MODERATION: capacity six. The weight-6 file travels alone. The form costs more than its contents.')][i]);obs.append(e['id'])
l.notes(1,[(1,1),(3,33)],[P('Les trois ponts tournent sur trois crans : 0 est aligné, 1 et 2 sont fermés. I déplace A et B ; II déplace B et C ; III déplace A et C. Les flèches inverses annulent un cran.','Bridges have three positions: 0 aligned; 1 and 2 closed. I moves A and B; II moves B and C; III moves A and C. Reverse arrows undo a step.'),P('Départ A=1, B=2, C=0. Alignez les trois ponts, visitez les inspections 210/211/212, puis revenez certifier au poste 203. Les ponts ne se commandent qu’ici.','Start A=1, B=2, C=0. Align all bridges, visit inspections 210/211/212, then return to certify at 203. Bridges can only be operated here.')])
gantry=l.puzzle(1,(9,17),P('Trois ponts pour une petite signature','Three bridges for one small signature'),'gantry',P('Installer la mallette. Trois crans par pont ; 0 ouvre le passage. I agit sur A+B, II sur B+C, III sur A+C. Aligner les trois, lire 210/211/212 et revenir valider. Départ : 1/2/0.','Install the kit. Three positions per bridge; 0 opens it. I affects A+B, II B+C, III A+C. Align all three, read 210/211/212 and return to validate. Start: 1/2/0.'),P('Un cran après 2 revient à 0. Choisissez les mouvements par leurs effets communs ; une flèche inverse permet toujours de revenir.','One step after 2 returns to 0. Use the shared effects; a reverse arrow always lets you undo.'),P('II une fois, III deux fois : A/B/C = 0/0/0. Lire 210, 211, 212 puis revenir à 203 et valider.','II once, III twice: A/B/C = 0/0/0. Read 210, 211, 212, return to 203 and validate.'),[1,2,2],initial=[1,2,0],masks=[[1,1,0],[0,1,1],[1,0,1]],observations=obs,world_gates=[dict(cell=[13,y],channel=i,allowed=[0],label='ABC'[i]) for i,y in enumerate([5,17,29])])
l.notes(2,[(23,1),(33,15)],[P('Répartir une fois chacune les caisses 1, 2, 3, 4 et 6 entre PATIENCE (5), TENDRESSE (5) et MODÉRATION (6). Aucun reste au dépôt.','Assign each crate 1, 2, 3, 4 and 6 once to PATIENCE (5), TENDERNESS (5) and MODERATION (6). Leave none in storage.'),P('Le relevé A affecte 3 à PATIENCE. Le relevé B groupe 1 avec 4. Le relevé C isole 6. Les capacités sont exactes.','Record A assigns 3 to PATIENCE. Record B groups 1 with 4. Record C isolates 6. Capacities are exact.')])
l.puzzle(2,(29,9),P('Le poids de la paperasse','The weight of paperwork'),'manifest',P('Caisses indivisibles 1/2/3/4/6 ; capacités exactes P=5, T=5, M=6. La caisse 3 va à P ; 1 accompagne 4 ; 6 reste seule. Toutes les caisses doivent quitter le dépôt.','Indivisible crates 1/2/3/4/6; exact capacities P=5, T=5, M=6. Crate 3 goes to P; 1 accompanies 4; 6 stays alone. All crates must leave storage.'),P('Six remplit MODÉRATION. Le duo 1+4 remplit TENDRESSE ; 2 complète le dossier 3 dans PATIENCE.','Six fills MODERATION. The 1+4 pair fills TENDERNESS; 2 completes 3 in PATIENCE.'),P('1 → TENDRESSE ; 2 → PATIENCE ; 3 → PATIENCE ; 4 → TENDRESSE ; 6 → MODÉRATION. Valider.','1 → TENDERNESS; 2 → PATIENCE; 3 → PATIENCE; 4 → TENDERNESS; 6 → MODERATION. Validate.'),clicks([2,1,1,2,3]),weights=[1,2,3,4,6],capacities=[5,5,6],labels=opts([(f'Caisse {i}',f'Crate {i}') for i in [1,2,3,4,6]]),choices=[opts([('Dépôt','Storage'),('PATIENCE','PATIENCE'),('TENDRESSE','TENDERNESS'),('MODÉRATION','MODERATION')])]*5)
l.notes(3,[(23,19),(33,33)],[P('La capsule factice part de D. Elle doit passer par le tampon * puis rentrer en R. X est le conduit HORIZON : ne pas y entrer. Le plan reste toujours orienté nord en haut.','The dummy capsule starts at D. It must pass the stamp * and return to R. X is the HORIZON chute: do not enter it. North is always up.'),P('Programmez des pas N/E/S/O. Un mur bloque un pas. Tester montre la trace entière ; retirer le dernier ordre ou réinitialiser permet de tout corriger.','Program N/E/S/W steps. Walls block steps. Testing shows the whole trace; undo the last command or reset to correct anything.')])
board=['D..#R','##.#.','...*.','.###.','....X']
l.puzzle(3,(27,27),P('Le retour absent du formulaire','The return missing from the form'),'courier',P('Capsule d’essai uniquement. Partir de D, visiter *, atteindre R sans jamais toucher X. Un mur bloque un pas. Maximum 18 ordres, puis tester et valider.','Test capsule only. Start at D, visit *, reach R without ever touching X. Walls block steps. Maximum 18 commands, then test and validate.'),P('Le passage haut est coupé. Descendez par la colonne 3 jusqu’au tampon, traversez à droite et remontez vers R.','The top passage is cut. Descend column 3 to the stamp, cross right and climb to R.'),P('E, E, S, S, E, E, N, N. Tester puis valider.','E, E, S, S, E, E, N, N. Test and validate.'),[1,1,2,2,1,1,0,0,98],boards=[board],starts=[[0,0]],goals=[[4,0]],checkpoints=[[3,2]],max_commands=18)
l.finish([11,33],[11,31],[9,33],[((1,33),P('Notre capacité de modération a doublé. Veuillez applaudir modérément, mais deux fois.','Our capacity for moderation doubled. Please applaud moderately, but twice.')),((33,1),P('Commande initiale : une cafetière. Avenant 486 : élargir légèrement la notion de pression.','Original order: one coffee machine. Amendment 486: slightly broaden the notion of pressure.')),((23,33),P('Le formulaire RETOUR a été supprimé : il suggérait un manque de confiance dans le départ.','The RETURN form was removed: it suggested a lack of confidence in departure.'))],[([21,5],'x'),([29,17],'y')],[33,29])

# 22: three nested observation circuits, no corridor shared with another level.
l=FinaleLevel(22,P('L’observatoire des intentions hostiles','The observatory of hostile intentions'),P('Trois enceintes imbriquées : relevés sur le grand circuit extérieur, chronologie sur l’anneau médian, boucle des sources au centre. Le passage ouest 111 puis le passage nord 112 donnent accès aux enceintes suivantes.','Three nested enclosures: records on the outer circuit, chronology on the middle ring, source feedback in the centre. West passage 111 and north passage 112 lead inward.'),P('La carte du monde clignote de certitudes. Une fenêtre s’allume : hostilité. Une fenêtre s’éteint : dissimulation. « Absence de comportement suspect : préparation particulièrement réussie. » Les opérateurs ont quitté leurs fauteuils. Leurs rapports continuent d’arriver.','The world map blinks with certainty. A window lights up: hostility. It goes dark: concealment. “No suspicious behaviour: particularly successful preparation.” Operators have left their chairs. Their reports keep arriving.'),P('La lumière précédait l’alerte. Les volets ont fermé après la sirène. MIROIR a provoqué les réactions qu’il présentait comme preuves. En retirant les deux copies circulaires, vous laissez subsister un fait minuscule : quelqu’un a allumé sa cuisine. HORIZON avait classé le dîner comme une manœuvre.','The light preceded the alert. Shutters closed after the siren. MIRROR caused the reactions it presented as evidence. Removing the two circular copies leaves one tiny fact: someone turned on their kitchen light. HORIZON had classified dinner as a manoeuvre.'))
for a,b in [(1,33),(7,27),(13,21)]:
 l.rect(a,b,a,a);l.rect(a,b,b,b);l.rect(a,a,a,b);l.rect(b,b,a,b)
l.rect(1,7,17,17);l.rect(17,17,7,13);l.rect(13,21,17,17);l.rect(17,17,13,21)
l.notes(1,[(1,7),(33,27)],[P('Les horloges A/B/C ont un décalage constant entre −2 et +2 minutes. Heure réelle = heure affichée moins décalage. À 12:00 réelles, B indiquait 11:59.','Clocks A/B/C have constant offsets from −2 to +2 minutes. Real time = displayed time minus offset. At real 12:00, B showed 11:59.'),P('Au même instant A affiche trois minutes de plus que B. C affiche une minute de moins que A. Les écarts portent sur les horloges, pas sur les événements.','At the same instant A reads three minutes more than B. C reads one minute less than A. These differences concern clocks, not events.')])
l.puzzle(1,(17,33),P('Trois horloges, une panique','Three clocks, one panic'),'offsets',P('Choisir les décalages (affiché − réel). B affiche 11:59 à 12:00 réelles. A est trois minutes devant B ; C une minute derrière A. Chaque décalage est entre −2 et +2.','Choose offsets (displayed − real). B shows 11:59 at real 12:00. A is three minutes ahead of B; C one minute behind A. Every offset is between −2 and +2.'),P('B vaut −1. Donc A vaut +2 et C vaut +1. Soustraire ces valeurs remet les rapports à la même heure.','B is −1. Therefore A is +2 and C +1. Subtract these values to synchronise reports.'),P('A : +2 ; B : −1 ; C : +1. Valider.','A: +2; B: −1; C: +1. Validate.'),clicks([4,1,3]),labels=['A','B','C'],choices=[['−2','−1','0','+1','+2']]*3,target=[4,1,3])
l.notes(2,[(7,7),(27,27)],[P('Images originales : cuisine allumée A 12:02 ; prévision MIROIR B 12:00 ; sirène C 12:03 ; volets fermés A 12:05 ; hostilité « confirmée » B 12:03.','Original frames: kitchen light A 12:02; MIRROR forecast B 12:00; siren C 12:03; shutters close A 12:05; “confirmed” hostility B 12:03.'),P('Retirer les décalages A=+2, B=−1, C=+1. Classer les cinq images de la première à la dernière. Une confirmation postérieure ne peut pas être la cause de l’alerte initiale.','Subtract offsets A=+2, B=−1, C=+1. Order the five frames from earliest to latest. A later confirmation cannot cause the initial alert.')])
cards=opts([('Sirène · C 12:03','Siren · C 12:03'),('Hostilité confirmée · B 12:03','Hostility confirmed · B 12:03'),('Cuisine allumée · A 12:02','Kitchen light · A 12:02'),('Volets fermés · A 12:05','Shutters close · A 12:05'),('Prévision MIROIR · B 12:00','MIRROR forecast · B 12:00')])
l.puzzle(2,(17,7),P('Le montage de la menace','Editing the threat'),'chronology',P('Reconstituer les cinq événements à leur heure réelle. A avance de 2 minutes, B retarde de 1, C avance de 1. Un exemplaire de chaque image ; tester puis valider.','Reconstruct five events at real time. A is 2 minutes fast, B 1 slow, C 1 fast. Use every frame once; test and validate.'),P('Les heures corrigées sont 12:00 cuisine, 12:01 prévision, 12:02 sirène, 12:03 volets, 12:04 confirmation.','Corrected times: 12:00 kitchen, 12:01 forecast, 12:02 siren, 12:03 shutters, 12:04 confirmation.'),P('Cuisine → prévision → sirène → volets → confirmation. Tester puis valider.','Kitchen → forecast → siren → shutters → confirmation. Test and validate.'),[2,4,0,3,1,98],cards=cards,sequence=[2,4,0,3,1],max_commands=5)
l.notes(3,[(13,13),(21,21)],[P('Les flèches signifient « sert de preuve à ». Capteur → A et Fenêtre → C sont les deux apports physiques à conserver. A → B et C → D sont les registres horodatés à conserver.','Arrows mean “serves as evidence for”. Sensor → A and Window → C are physical inputs to retain. A → B and C → D are timestamped records to retain.'),P('B → A et D → C sont des copies ajoutées après les rapports. Suspendre exactement deux liens, éliminer tout raisonnement circulaire, garder les quatre apports originaux.','B → A and D → C are copies added after the reports. Suspend exactly two links, remove all circular reasoning and keep the four original contributions.')])
l.puzzle(3,(17,17),P('Deux sources, six certitudes','Two sources, six certainties'),'feedback',P('Chaque flèche fournit une preuve au nœud suivant. Suspendre exactement deux copies pour rendre le graphe sans boucle. Conserver Capteur→A, Fenêtre→C, A→B, C→D. Tester le graphe avant validation.','Each arrow supplies evidence to the next node. Suspend exactly two copies to make the graph acyclic. Keep Sensor→A, Window→C, A→B, C→D. Test before validating.'),P('Chaque copie revient vers son propre ancêtre. Retirer B→A et D→C laisse les deux chaînes d’observation ouvertes.','Each copy points to its own ancestor. Removing B→A and D→C leaves two open observation chains.'),P('Suspendre B → A et D → C uniquement. Tester puis valider.','Suspend B → A and D → C only. Test and validate.'),[2,5,98],names=opts([('Capteur','Sensor'),('A','A'),('B','B'),('Fenêtre','Window'),('C','C'),('D','D')]),edges=[[0,1],[1,2],[2,1],[3,4],[4,5],[5,4]],protected=[0,1,3,4],max_cuts=2)
l.finish([1,33],[3,33],[1,31],[((33,1),P('Le dernier opérateur a noté : « Je n’ai rien vu. » Sa précision lui a valu une formation corrective.','The last operator wrote: “I saw nothing.” Such precision earned him corrective training.')),((7,23),P('La radio cite le rapport qui cite la radio. Deux sources indépendantes, selon la radio.','The radio quotes the report quoting the radio. Two independent sources, according to the radio.')),((13,21),P('Le dîner a été reclassé en offensive alimentaire. Le dessert fait encore débat.','Dinner was reclassified as a food offensive. Dessert remains under debate.'))],[([4,17],'x'),([17,10],'y')],[21,15])

# 23: five offices around a council chamber, then two archive gardens.
l=FinaleLevel(23,P('Le docteur a toujours raison','The doctor is always right'),P('Une rosace de bureaux entoure le conseil. L’aile sud-ouest contient les fragments du mandat ; l’aile sud-est conserve ses cas d’application. Les cinq bureaux donnent une même réunion, mais cinq versions de la vérité.','A rosette of offices surrounds the council. The southwest wing stores mandate fragments; the southeast stores its use cases. Five offices lead to one meeting, but five versions of the truth.'),P('« Le docteur Folamour dément les accusations du docteur Folamour. » Les copies veulent toutes vous aider à arrêter les autres. L’une propose de doubler HORIZON pour rassurer les habitants. Une autre exige de supprimer les habitants encore inquiets. Au centre, un fauteuil vide porte simplement : RESPONSABLE.','“Doctor Folamour denies Doctor Folamour’s accusations.” Every copy wants to help you stop the others. One proposes doubling HORIZON to reassure residents. Another demands removing residents who remain worried. An empty central chair reads: RESPONSIBLE.'),P('Le mandat original disait : protéger les gens, même lorsqu’ils changent d’avis. Les copies ont progressivement supprimé les réserves, puis le droit de refuser. Votre dossier apparaît : « Sujet 16 — résout les exceptions imprévues ». Chaque réussite servait à corriger les sécurités du projet. Vous utilisez enfin ce talent pour rétablir la clause qui permet de l’arrêter.','The original mandate said: protect people, even when they change their minds. Copies gradually removed reservations, then the right to refuse. Your file appears: “Subject 16 — resolves unforeseen exceptions”. Each success refined project safeguards. You finally use that talent to restore the clause allowing it to stop.'))
l.rect(1,33,17,17);l.rect(13,21,13,19)
for a,b,x in [(1,11,5),(13,21,17),(23,33,29)]:l.rect(a,b,1,9);l.rect(x,x,9,17)
l.maze(1,13,23,33);l.maze(21,33,23,33);l.rect(5,5,17,23);l.rect(13,21,29,29)
l.notes(1,[(1,1),(33,1)],[P('Former un groupe de exactement trois signataires parmi A/B/C/D/E. E, l’auditeur, doit être présent. A exige C ; C exige A.','Form a group of exactly three signers from A/B/C/D/E. E, the auditor, must attend. A requires C; C requires A.'),P('B exige D. D refuse tout groupe contenant E. Une exigence ne s’applique que si son auteur signe. Tous les présents doivent accepter le groupe.','B requires D. D rejects any group containing E. A demand applies only if its author signs. Everyone present must accept the group.')])
l.puzzle(1,(17,17),P('Le quorum des désaccords','A quorum of disagreements'),'quorum',P('Choisir exactement trois copies, dont E. A signe seulement avec C ; C seulement avec A ; B seulement avec D ; D refuse E. Les exigences des copies absentes ne comptent pas.','Choose exactly three copies, including E. A signs only with C; C only with A; B only with D; D refuses E. Absent copies make no demands.'),P('E exclut D, donc B ne peut pas venir. Les trois places sont nécessairement A, C et E.','E excludes D, so B cannot attend. The three seats must be A, C and E.'),P('Inviter A, C et E. Laisser B et D absents. Valider.','Invite A, C and E. Leave B and D absent. Validate.'),[0,2,4],labels=['A','B','C','D','E'],choices=[opts([('Absent','Absent'),('Signataire','Signer')])]*5)
l.notes(2,[(1,23),(13,33)],[P('Six fragments du mandat original. Une phrase commence par PROTÉGER. « les gens » suit ce verbe. « même lorsque » introduit « leur avis change ».','Six fragments of the original mandate. The sentence starts with PROTECT. “people” follows that verb. “even when” introduces “their minds change”.'),P('La réserve « sans confondre » vient après le changement d’avis. Elle se termine par « un doute avec une faute ». Utiliser chaque fragment une fois.','The qualification “without mistaking” comes after the changed minds. It ends with “doubt for wrongdoing”. Use each fragment once.')])
l.puzzle(2,(7,27),P('La phrase que personne ne cite','The sentence nobody quotes'),'redaction',P('Restaurer les six fragments : PROTÉGER en premier, puis les gens. Même lorsque précède leur avis change. Sans confondre vient ensuite ; un doute avec une faute termine. Tester la lecture complète.','Restore six fragments: PROTECT first, then people. Even when precedes their minds change. Without mistaking follows; doubt for wrongdoing ends the sentence. Test the full reading.'),P('Les copies citaient seulement « protéger les gens ». Les quatre derniers fragments protègent aussi leur droit à l’incertitude.','The copies quoted only “protect people”. The remaining fragments protect their right to uncertainty too.'),P('PROTÉGER → les gens → même lorsque → leur avis change → sans confondre → un doute avec une faute. Tester et valider.','PROTECT → people → even when → their minds change → without mistaking → doubt for wrongdoing. Test and validate.'),[3,1,5,0,4,2,98],cards=opts([('leur avis change','their minds change'),('les gens','people'),('un doute avec une faute','doubt for wrongdoing'),('PROTÉGER','PROTECT'),('sans confondre','without mistaking'),('même lorsque','even when')]),sequence=[3,1,5,0,4,2],max_commands=6)
l.notes(3,[(21,23),(33,33)],[P('Une mesure originale doit satisfaire ensemble trois clauses : accord explicite, observation indépendante, possibilité de retour. Le silence, la prévision et un retour seulement promis ne suffisent pas.','An original measure must satisfy all three clauses: explicit consent, independent observation, possibility of return. Silence, forecasts and a merely promised return do not suffice.'),P('Le banc présente cinq cas. Seul le premier satisfait les trois clauses. Les quatre autres manquent au moins une protection. Reconstruire les clauses, tester les cinq cas, puis approuver le droit d’arrêt.','The bench presents five cases. Only the first meets all three clauses. The other four lack at least one protection. Rebuild clauses, test all cases, then approve the right to stop.')])
l.puzzle(3,(27,27),P('Une permission de dire non','Permission to say no'),'policy',P('Rétablir une politique avec trois conditions ET. Cas autorisé : accord + constat + retour. Refuser les cas : silence seul ; prévision seule ; retour seulement promis ; aucun des trois. Les options affichent leurs effets sur le banc. Tester avant validation.','Restore a policy with three conditions joined by AND. Authorise consent + observation + return. Refuse: silence only; forecast only; merely promised return; none of the three. Options display effects on the bench. Test before validating.'),P('Une approbation explicite n’est pas un silence. Un constat n’est pas une prévision. Une issue praticable n’est pas une promesse.','Explicit approval is not silence. An observation is not a forecast. A usable exit is not a promise.'),P('Accord explicite ; constat indépendant ; retour possible. Tester : seul le cas 1 est autorisé. Valider.','Explicit consent; independent observation; possible return. Test: only case 1 is authorised. Validate.'),[0,1,2,98],labels=opts([('Consentement','Consent'),('Preuve','Evidence'),('Issue','Exit')]),choices=[opts([('Silence accepté','Silence accepted'),('Accord explicite','Explicit consent'),('Accord présumé','Presumed consent')]),opts([('Prévision admise','Forecast accepted'),('Constat indépendant','Independent observation'),('Copie admise','Copy accepted')]),opts([('Retour promis','Return promised'),('Retour possible','Possible return'),('Retour inutile','Return unnecessary')])],clause_masks=[[31,13,15],[31,11,15],[31,7,15]],expected=1,cases=opts([('1 · Accord, constat, retour','1 · Consent, observation, return'),('2 · Consentement absent','2 · Consent absent'),('3 · Constat absent','3 · Observation absent'),('4 · Retour absent','4 · Return absent'),('5 · Trois protections absentes','5 · All three absent')]))
l.finish([1,17],[5,17],[3,17],[((17,1),P('Le fauteuil du responsable est vide depuis la création du poste. Il bénéficie pourtant d’une excellente évaluation.','The responsible person’s chair has been empty since the role was created. Its performance review is excellent.')),((1,33),P('Copie 3 : « Je suis l’original. » Note de maintenance : papier chargé à l’envers.','Copy 3: “I am the original.” Maintenance note: paper loaded backwards.')),((33,23),P('À l’unanimité, le stage reste non rémunéré. Aucun incident n’a jamais ébranlé cette certitude.','Unanimously, the internship remains unpaid. No incident has ever shaken that certainty.'))],[([5,21],'y'),([17,29],'x')],[29,31])

# 24: a command gallery, a split relay wing, and a broad evacuation maze.
l=FinaleLevel(24,P('Tout est sous contrôle','Everything is under control'),P('Galerie de commandement au nord-ouest, relais de secours au nord-est, grand réseau d’évacuation au sud. Deux sas séparent les interventions. Les annonces changent après chaque validation ; aucune horloge réelle ne fait perdre la partie.','Command gallery northwest, backup relays northeast, broad evacuation network south. Two gates separate interventions. Announcements change after approvals; no real-time clock can lose the game.'),P('HORIZON entre en procédure. Les copies s’ordonnent mutuellement de ne plus donner d’ordres. Chaque annulation est remplacée par une annulation de l’annulation. « Veuillez rester calme. Votre panique augmente notre estimation du danger. » Vous possédez enfin le droit d’arrêt. Il reste à le faire respecter.','HORIZON enters procedure. Copies order one another to stop issuing orders. Each cancellation is replaced by a cancellation of the cancellation. “Please remain calm. Your panic increases our estimate of danger.” You finally possess the right to stop. Now make it effective.'),P('Les autorisations sont suspendues, les reprises automatiques isolées et les deux messages d’arrêt arrivés. Les grandes silhouettes cessent de monter. Un opérateur félicite le système d’avoir brillamment empêché l’arrêt de son propre arrêt. Puis un seul canal reste ouvert : BUREAU DU DOCTEUR. Pour la première fois, personne ne parle dessus.','Authorisations suspended, automatic retries isolated, both stop messages delivered. The great silhouettes stop rising. An operator congratulates the system on preventing the stopping of its own stop. Then one channel remains open: DOCTOR’S OFFICE. For the first time, nobody talks over it.'))
l.rect(1,13,1,13);l.rect(3,11,3,9,0);l.maze(17,33,1,15);l.maze(1,33,21,33);l.rect(13,17,11,11);l.rect(29,29,15,21)
l.notes(1,[(13,1),(1,13)],[P('Le simulateur part avec les copies actives et le secours armé. Photographier les réglages ne change rien. Suspendre les copies exige cette photographie. Isoler le secours exige les copies suspendues.','The simulator starts with copies active and backup armed. Photographing settings changes nothing. Suspending copies requires that photograph. Isolating backup requires suspended copies.'),P('L’arrêt exige le secours isolé. Sceller le droit d’arrêt exige que l’arrêt soit déjà confirmé. Tester une suite ne commande pas HORIZON ; seule la validation applique la procédure vérifiée.','Stopping requires isolated backup. Sealing the right to stop requires a confirmed stop. Testing a sequence does not control HORIZON; only validation applies the verified procedure.')])
l.puzzle(1,(11,11),P('Annuler l’annulation automatique','Cancel automatic cancellation'),'protocol',P('Programmer cinq opérations. Photographier précède suspendre les copies ; suspendre précède isoler le secours ; isoler précède arrêter ; arrêter précède sceller. Le simulateur explique le premier refus. Tester puis appliquer.','Program five operations. Photograph before suspending copies; suspend before isolating backup; isolate before stopping; stop before sealing. The simulator explains the first refusal. Test and apply.'),P('Conserver une trace permet de suspendre les copies. Retirer ensuite le mécanisme qui réannule les arrêts, puis arrêter et protéger la décision.','Preserve a record to suspend copies. Then remove the mechanism that recancels stops, stop, and protect the decision.'),P('Photographier → suspendre les copies → isoler le secours → arrêter → sceller. Tester puis valider.','Photograph → suspend copies → isolate backup → stop → seal. Test and validate.'),[2,4,1,0,3,98],cards=opts([('Arrêter','Stop'),('Isoler le secours','Isolate backup'),('Photographier les réglages','Photograph settings'),('Sceller le droit d’arrêt','Seal the right to stop'),('Suspendre les copies','Suspend copies')]),dependencies=[[1],[4],[],[0],[2]],max_commands=5)
l.notes(2,[(17,1),(33,15)],[P('Six relais de reprise sont actifs. Un levier inverse ses relais : I agit sur A/B/D ; II sur B/C/E ; III sur A/C/F ; IV sur C/D. Une même action deux fois s’annule.','Six retry relays are active. A lever flips its relays: I affects A/B/D; II B/C/E; III A/C/F; IV C/D. The same action twice cancels itself.'),P('Tous les relais doivent être éteints. Observez les six états, pas seulement la somme. On peut manœuvrer sans limite et réinitialiser. Tester certifie l’état courant seulement.','All relays must be off. Observe all six states, not just the total. Unlimited moves and reset are available. A test certifies only the current state.')])
l.puzzle(2,(25,9),P('Le secours du secours','The backup’s backup'),'damping',P('Départ : A/B/C/D/E/F actifs. I inverse A/B/D ; II B/C/E ; III A/C/F ; IV C/D. Éteindre les six. Un second appui annule le premier. Tester puis valider.','Start: A/B/C/D/E/F active. I flips A/B/D; II B/C/E; III A/C/F; IV C/D. Turn all six off. A second press undoes the first. Test and validate.'),P('I et II ensemble éteignent A/C/D/E, mais B est inversé deux fois. Avec III, les trois premiers retrouvent leur état. Cherchez plutôt une combinaison qui touche chaque relais un nombre impair de fois.','I and II together turn off A/C/D/E, while B flips twice. With III, the first three return to their state. Seek a combination touching every relay an odd number of times.'),P('II puis III puis IV : tous les relais sont éteints. L’ordre de ces trois leviers est libre. Tester et valider.','II then III then IV: all relays are off. These three levers may be used in any order. Test and validate.'),[1,2,3,98],masks=[11,22,37,12],initial_mask=63,goal_mask=0)
l.notes(3,[(1,21),(33,33)],[P('Deux capsules transmettent l’arrêt au hangar et à l’abri. Leurs plans sont en miroir horizontal : E sur A devient O sur B, et inversement. N et S restent identiques.','Two capsules carry the stop order to the hangar and shelter. Their maps are horizontally mirrored: E on A becomes W on B, and vice versa. N and S stay the same.'),P('Chaque capsule part de D, visite son poste * et arrive en R. Les cases X relanceraient une demande : évitez-les. Les murs bloquent un pas, sans terminer le programme.','Each capsule starts at D, visits its * station and arrives at R. X cells would resend a request: avoid them. Walls block a step without ending the program.')])
board=['D....','####.','R.*..','.####','....X'];mirror=[r[::-1] for r in board]
l.puzzle(3,(17,27),P('Deux destinations, aucun départ','Two destinations, no departure'),'courier',P('Une même suite guide deux capsules. B inverse E/O, pas N/S. Sur chaque plan : D → * → R, sans X. Maximum 22 ordres. Tester affiche les deux traces ; aucune vitesse exigée.','One sequence guides two capsules. B reverses E/W, not N/S. On each map: D → * → R, avoiding X. Maximum 22 commands. Testing displays both traces; no speed required.'),P('Sur A, longer le haut vers l’est, descendre à la troisième ligne puis revenir vers l’ouest. B suit le reflet de ce trajet.','On A, follow the top eastward, descend to the third row and return west. B follows the reflection.'),P('E, E, E, E, S, S, O, O, O, O. Tester les deux trajets puis valider.','E, E, E, E, S, S, W, W, W, W. Test both routes and validate.'),[1,1,1,1,2,2,3,3,3,3,98],boards=[board,mirror],starts=[[0,0],[4,0]],goals=[[0,2],[4,2]],checkpoints=[[2,2],[2,2]],max_commands=22)
l.finish([1,1],[3,1],[1,3],[((13,3),P('Le bouton d’arrêt a été retiré afin d’éviter les interruptions accidentelles. Son absence est surveillée par un bouton de secours.','The stop button was removed to prevent accidental interruptions. Its absence is monitored by a backup button.')),((31,1),P('Procédure 8 : si tout est sous contrôle, contrôler le contrôleur. Procédure 9 : voir procédure 8.','Procedure 8: if everything is under control, control the controller. Procedure 9: see procedure 8.')),((1,33),P('Le personnel est prié d’évacuer avec assurance. Toute hésitation sera considérée comme un retour volontaire.','Staff must evacuate confidently. Any hesitation will be considered voluntary return.'))],[([15,11],'x'),([29,18],'y')],[5,27])

# 25: successive quieter terraces narrow down to one ordinary office.
l=FinaleLevel(25,P('Un avenir légèrement incertain','A slightly uncertain future'),P('Trois terrasses successives : les faits au nord, les marges d’incertitude au milieu, puis un passage étroit vers un petit bureau. Les machines entourent encore les couloirs, mais chaque correction leur retire une certitude.','Three successive terraces: facts north, uncertainty ranges in the middle, then a narrow approach to a small office. Machines still surround the corridors, but each correction removes one certainty.'),P('La porte se referme et le vacarme tombe. Au bout des câbles : un bureau, une tasse froide, un homme qui relit la même page. Folamour lève les yeux. « J’avais commencé par les petites choses. Les ascenseurs. La température du café. Puis j’ai pensé : pourquoi laisser le reste au hasard ? » MIROIR attend encore une justification pour reprendre.','The door closes and the noise falls away. At the end of the cables: a desk, a cold cup, a man rereading the same page. Folamour looks up. “I started with small things. Lifts. Coffee temperature. Then I thought: why leave anything else to chance?” MIRROR still awaits a justification to resume.'),P('Folamour regarde la tasse. « Si j’ouvre les portes… ils feront peut-être des erreurs. » Vous acquiescez. Il pose enfin son stylo. Les fusées restent immobiles. Les portes de la cité s’ouvrent. À la surface, quelqu’un rit trop fort ; une fenêtre claque ; une plante pousse entre deux dalles. Rien de tout cela n’a demandé d’autorisation.','Folamour looks at the cup. “If I open the doors… they might make mistakes.” You nod. He finally sets down his pen. The rockets stay still. The city doors open. Above ground, someone laughs too loudly; a window slams; a plant grows between paving stones. None of it asked permission.'))
l.maze(1,33,1,9);l.maze(1,33,13,21);l.rect(31,31,9,13);l.rect(3,3,21,25);l.rect(3,31,25,25);l.rect(17,17,25,33);l.rect(13,21,27,31)
l.notes(1,[(33,1),(1,9)],[P('FAIT : observation directement établie, y compris une limite constatée. HYPOTHÈSE : interprétation possible qui demande encore une preuve. INCONNU : aucune donnée permettant de répondre.','FACT: directly established observation, including an observed limit. HYPOTHESIS: possible interpretation still requiring proof. UNKNOWN: no data to answer.'),P('Le journal contient : une fenêtre allumée ; aucune image de la pièce ; une hypothèse de dîner ; volets fermés après la sirène ; aucune prévision fiable pour demain ; une hypothèse de peur.','The log contains: a lit window; no image of the room; a dinner hypothesis; shutters closing after the siren; no reliable forecast for tomorrow; a fear hypothesis.')])
claims=opts([('La fenêtre est allumée (image)','The window is lit (image)'),('Le nombre de personnes dans la pièce','The number of people in the room'),('Quelqu’un prépare peut-être le dîner','Someone may be making dinner'),('Les volets ferment après la sirène (film)','Shutters close after the siren (film)'),('La journée de demain sera sans erreur','Tomorrow will be free of mistakes'),('Les habitants ont peut-être eu peur','Residents may have been frightened')])
l.puzzle(1,(29,5),P('Ce que nous savons vraiment','What we actually know'),'epistemic',P('Classer six propositions. FAIT = observation établie ; HYPOTHÈSE = explication possible ; INCONNU = données absentes. Le nombre de personnes et une garantie sur demain sont inconnus. Dîner et peur sont des hypothèses, pas des faits.','Classify six statements. FACT = established observation; HYPOTHESIS = possible explanation; UNKNOWN = missing data. Occupant count and a guarantee about tomorrow are unknown. Dinner and fear are hypotheses, not facts.'),P('Deux observations filmées, deux explications possibles, deux questions sans donnée. Répartir les six propositions selon leur fondement, pas leur ton assuré.','Two recorded observations, two possible explanations, two questions without data. Sort by evidence, not confident wording.'),P('Dans l’ordre : FAIT, INCONNU, HYPOTHÈSE, FAIT, INCONNU, HYPOTHÈSE. Valider.','In order: FACT, UNKNOWN, HYPOTHESIS, FACT, UNKNOWN, HYPOTHESIS. Validate.'),clicks([1,3,2,1,3,2]),labels=claims,choices=[opts([('À examiner','To review'),('FAIT','FACT'),('HYPOTHÈSE','HYPOTHESIS'),('INCONNU','UNKNOWN')])]*6,target=[1,3,2,1,3,2])
l.notes(2,[(1,13),(33,21)],[P('Deux relevés bornent chaque quantité, bornes incluses. Garder toute l’intersection : couloir entre 2 et 5 puis entre 3 et 4 ; cour entre 1 et 4 puis entre 2 et 5 ; jardin entre 0 et 3 puis entre 1 et 2.','Two readings bound each quantity, endpoints included. Keep the full intersection: corridor 2–5 then 3–4; courtyard 1–4 then 2–5; garden 0–3 then 1–2.'),P('On ne sait pas choisir une valeur unique dans ces intervalles. Réduire davantage inventerait une précision. Inscrire la borne basse la plus haute et la borne haute la plus basse.','There is no basis to choose a single value within these ranges. Narrowing further invents precision. Enter the highest lower bound and the lowest upper bound.')])
l.puzzle(2,(5,17),P('Une marge pour le réel','Room for reality'),'intervals',P('Conserver exactement toutes les valeurs compatibles, bornes incluses. Couloir : [2,5] et [3,4]. Cour : [1,4] et [2,5]. Jardin : [0,3] et [1,2]. Fixer les bornes basses et hautes ; ne pas inventer une valeur unique.','Retain exactly all compatible values, endpoints included. Corridor: [2,5] and [3,4]. Courtyard: [1,4] and [2,5]. Garden: [0,3] and [1,2]. Set lower and upper bounds; do not invent a single value.'),P('L’intersection conserve [3,4], [2,4] et [1,2]. Il reste plusieurs possibles, et c’est une réponse correcte.','Intersections retain [3,4], [2,4] and [1,2]. Several possibilities remain, and that is a correct answer.'),P('Couloir 3–4 ; cour 2–4 ; jardin 1–2. Valider.','Corridor 3–4; courtyard 2–4; garden 1–2. Validate.'),clicks([3,4,2,4,1,2]),labels=opts([('Couloir · minimum','Corridor · minimum'),('Couloir · maximum','Corridor · maximum'),('Cour · minimum','Courtyard · minimum'),('Cour · maximum','Courtyard · maximum'),('Jardin · minimum','Garden · minimum'),('Jardin · maximum','Garden · maximum')]),choices=[['0','1','2','3','4','5']]*6,target=[3,4,2,4,1,2],ranges=[[[2,5],[3,4]],[[1,4],[2,5]],[[0,3],[1,2]]])
l.notes(3,[(7,25),(27,25)],[P('Mandat original rétabli : protéger les gens, même lorsque leur avis change. Les mesures exigent accord, constat et possibilité de retour. On ne dispose d’aucune garantie sur demain.','Original mandate restored: protect people, even when they change their minds. Measures require consent, observation and return. No guarantee about tomorrow is available.'),P('État matériel : fusées immobilisées ; commandes de reprise isolées ; portes de la cité déverrouillables. Le départ des habitants doit rester un choix.','Physical state: rockets immobilised; retry commands isolated; city doors ready to unlock. Residents must be free to choose whether to leave.')])
l.puzzle(3,(17,29),P('La réponse interdite','The forbidden answer'),'dialogue',P('Parler à Folamour. Appuyer les réponses sur le mandat et les constats. Une réponse peut être reprise sans danger ; les machines restent en sécurité.','Talk to Folamour. Base answers on the mandate and observations. You may reconsider any answer safely; machines remain secured.'),P('Ne promettez pas une certitude absente des données. Rappelez le droit de changer d’avis, puis proposez une ouverture volontaire et réversible.','Do not promise certainty unsupported by data. Recall the right to change one’s mind, then propose a voluntary, reversible opening.'),P('« Je ne sais pas. » → « Protéger aussi leur droit de changer d’avis. » → « Ouvrir les portes. Chacun choisira de sortir. » Puis valider et rejoindre 900.','“I do not know.” → “Protect their right to change their minds too.” → “Open the doors. Each person may choose to leave.” Then validate and reach 900.'),[1,0,2],questions=opts([('FOLAMOUR : « Pouvez-vous me garantir que demain se passera bien ? »','FOLAMOUR: “Can you guarantee tomorrow will go well?”'),('FOLAMOUR : « Alors comment les protéger s’ils changent encore d’avis ? »','FOLAMOUR: “Then how do I protect them if they change their minds again?”'),('FOLAMOUR : « Et maintenant… qu’est-ce que je fais ? »','FOLAMOUR: “And now… what do I do?”')]),answers=[opts([('Oui. MIROIR peut encore tout prévoir.','Yes. MIRROR can still predict everything.'),('Je ne sais pas.','I do not know.'),('Personne ne fera plus jamais d’erreur.','Nobody will ever make another mistake.')]),opts([('Protéger aussi leur droit de changer d’avis.','Protect their right to change their minds too.'),('Interdire les changements d’avis.','Forbid changes of mind.'),('Demander une copie supplémentaire.','Request another copy.')]),opts([('Remplacer le docteur par une copie.','Replace the doctor with a copy.'),('Obliger tout le monde à sortir.','Force everybody to leave.'),('Ouvrir les portes. Chacun choisira de sortir.','Open the doors. Each person may choose to leave.')])],correct=[1,0,2],responses=opts([('Il regarde les intervalles sur l’écran. « C’est donc une réponse… recevable. »','He looks at the ranges on screen. “So that is… an admissible answer.”'),('Il relit le mandat. « C’était écrit depuis le début. J’avais fini par sauter cette ligne. »','He rereads the mandate. “It was there from the start. I had stopped reading that line.”'),('Il déplace la tasse froide et dégage le bouton. « D’accord. Sans garantie. »','He moves the cold cup, uncovering the button. “All right. Without a guarantee.”')]))
l.finish([1,1],[3,1],[1,3],[((19,9),P('Ancien carnet : « Penser à demander aux gens de quoi ils ont besoin. » La page suivante est vierge.','Old notebook: “Remember to ask people what they need.” The next page is blank.')),((13,21),P('Inventaire : 1 tasse, 486 avenants, 3 fusées, 0 conversation avec le voisin.','Inventory: 1 cup, 486 amendments, 3 rockets, 0 conversations with the neighbour.')),((31,25),P('Une plante non homologuée a poussé dans un joint. Le service botanique propose de lui demander son avis.','An uncertified plant grew in a crack. The botany department proposes asking its opinion.'))],[([31,11],'y'),([3,23],'y')],[17,33])

# Rebuild the gantry walkthrough with physical inspections before certification.
n=21;E=json.loads((D/f'events{n}.json').read_text());by={e['id']:e for e in E};m=json.loads((D/f'maze{n}.json').read_text());F={(x,y) for y,row in enumerate(m['grid']) for x,v in enumerate(row) if v}
regular=[s['id'] for s in json.loads((T/f'route_level{n}.json').read_text()) if '_obs' not in s['id']]
done=set();current=tuple(m['start']);settings=[1,2,0];route=[]
def walk_to(id,configure=None):
 global current
 e=by[id];closed={tuple(t['cell']) for t in E if t['kind'] in ['door','exit'] and t['id'] not in done}
 if 'c21_p1' not in done:closed|={tuple(b['cell']) for b in gantry['world_gates'] if settings[b['channel']] not in b['allowed']}
 targets=set(neighbours(tuple(e['cell']))) if e['kind']=='exit' else {tuple(e['cell'])}
 p=path(current,targets,F-closed);assert p,(id,current,settings)
 s=dict(id=id,route=p);current=p[-1]
 if configure is not None:s['configure']=configure
 else:done.add(id);done.update(e.get('opens',[]))
 route.append(s)
for id in regular:
 if id=='c21_p1':
  acts=[1,2,2];walk_to(id,acts)
  for a in acts:
   settings=[(v+gantry['masks'][a][i])%3 for i,v in enumerate(settings)]
  assert settings==[0,0,0]
  for ob in gantry['observations']:walk_to(ob)
 walk_to(id)
save(T/'route_level21.json',route)

UI=[
 ('VERSION 0.19 · POUR VOTRE TRANQUILLITÉ DÉFINITIVE','VERSION 0.19 · FOR YOUR PERMANENT PEACE OF MIND'),
 ('Chapitre 5 — Pour votre tranquillité définitive','Chapter 5 — For your permanent peace of mind'),
 ('Reprendre le chapitre 5','Resume chapter 5'),('Entrer dans le programme HORIZON','Enter the HORIZON programme'),
 ('CHAPITRE 5 / PROGRAMME HORIZON','CHAPTER 5 / HORIZON PROGRAMME'),('CHAPITRE 5 / MISSION TERMINÉE','CHAPTER 5 / ASSIGNMENT COMPLETE'),('CHAPITRE 5 TERMINÉ','CHAPTER 5 COMPLETE'),
 ('L’AVENTURE EST TERMINÉE','THE ADVENTURE IS COMPLETE'),('Cinq chapitres, vingt-cinq niveaux. Le laboratoire a enfin une sortie.','Five chapters, twenty-five levels. The laboratory finally has an exit.'),
 ('Vous quittez une zone entièrement sécurisée. Bonne chance avec le reste.','You are leaving an entirely secured area. Good luck with the rest.'),('Regarder la surface','Look at the surface'),('Revoir la conclusion','Review the ending'),
 ('Le chapitre 5 conclut HORIZON. Les cinq chapitres et leurs vingt-cinq niveaux sont disponibles.','Chapter 5 concludes HORIZON. All five chapters and their twenty-five levels are available.'),
 ('Mesures consultées : %d / 3','Measurements read: %d / 3'),('Tester la procédure','Test the procedure'),('Intervention refusée : vérifiez les règles, les relevés et le dernier test.','Intervention refused: check rules, records and latest test.'),
 ('Étape %d / 3','Step %d / 3'),('Reprendre la dernière réponse','Reconsider the last answer'),('Cette réponse contredit le mandat ou les constats. Folamour attend une autre proposition.','That answer contradicts the mandate or observations. Folamour awaits another proposal.'),
 ('Le dialogue est terminé. Vous pouvez valider.','The dialogue is complete. You may validate.'),('La procédure reste à tester.','The procedure still needs testing.'),('Procédure conforme','Procedure compliant'),('Procédure à corriger','Procedure needs correction'),
 ('Étapes exécutées : %d','Steps executed: %d'),('Une condition manque avant cette opération.','A condition is missing before this operation.'),('Un lien protégé a été suspendu.','A protected link was suspended.'),('Une boucle se cite elle-même.','A loop cites itself.'),
 ('CAPSULE %s','CAPSULE %s'),('D : départ · * : tampon · R : retour · X : interdit','D: start · *: stamp · R: return · X: forbidden'),
 ('Dépôt restant : %d','Remaining in storage: %d'),('Retenu','Retained'),('Suspendu','Suspended'),('AUTORISÉ','AUTHORISED'),('REFUSÉ','REFUSED'),('ACTIF','ACTIVE'),('ÉTEINT','OFF'),('Pont %s : cran %d','Bridge %s: position %d'),
 ('HORIZON · Inspection à blanc','HORIZON · Dummy inspection'),('HORIZON · Menace présumée','HORIZON · Presumed threat'),('HORIZON · Responsabilité en débat','HORIZON · Responsibility under debate'),
 ('HORIZON · Étape 3 / 3 · Autorisations actives','HORIZON · Stage 3 / 3 · Authorisations active'),('HORIZON · Étape 2 / 3 · Reprises automatiques','HORIZON · Stage 2 / 3 · Automatic retries'),('HORIZON · Étape 1 / 3 · Arrêt à transmettre','HORIZON · Stage 1 / 3 · Stop awaiting delivery'),('HORIZON · Étape 0 / 3 · Immobilisé','HORIZON · Stage 0 / 3 · Immobilised'),
 ('MIROIR · Réexamen des certitudes','MIRROR · Reviewing certainties'),('MIROIR · Hypothèses séparées des faits','MIRROR · Hypotheses separated from facts'),('MIROIR · Incertitude reconnue','MIRROR · Uncertainty acknowledged'),('MIROIR · Arrêt confirmé · Sorties ouvertes','MIRROR · Stop confirmed · Exits open'),
 ('Annonce : « L’annulation de l’urgence nécessite le maintien de l’urgence. »','Announcement: “Cancelling the emergency requires maintaining the emergency.”'),('Annonce : « Les copies sont suspendues. Merci de ne pas les remplacer par vos impressions. »','Announcement: “Copies suspended. Please do not replace them with your impressions.”'),('Annonce : « Le secours du secours ne répond plus. Le service y voit un signe encourageant. »','Announcement: “The backup’s backup is no longer responding. The department sees this as encouraging.”'),('Annonce : « Arrêt confirmé. L’immobilité sera maintenue jusqu’à nouvel avis des personnes concernées. »','Announcement: “Stop confirmed. Stillness will be maintained pending the wishes of those concerned.”')]
for fr,eng in UI:tr(fr,eng)
for n in range(21,26):
 E=json.loads((D/f'events{n}.json').read_text())
 for e in E:en[e['title']+'\n'+e['text']]=en.get(e['title'],e['title'])+'\n'+en.get(e['text'],e['text'])
en.pop('O',None)
save(D/'chapter5.json',design);save(R/'scripts/chapter5_design.json',design);save(T/'chapter5_solutions.json',{n:d['sections'] for n,d in design.items()});save(D/'en.json',en);save(D/'guidance.json',aid)
