"""Author chapter three: five distinct maps and fifteen hands-on experiments."""
from pathlib import Path
from collections import deque
import json, random
R=Path(__file__).resolve().parents[1];D=R/'game/data';T=R/'game/tests'
en=json.loads((D/'en.json').read_text());aid=json.loads((D/'guidance.json').read_text());design={}
def tr(fr,eng):en[fr]=eng;return fr
def pair(fr,eng):return [fr,eng]
def save(path,data):path.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n')
def neighbours(c):return [(c[0]+dx,c[1]+dy) for dx,dy in [(0,-1),(1,0),(0,1),(-1,0)]]
def path(a,targets,F):
 q=deque([a]);prev={a:None}
 while q:
  c=q.popleft()
  if c in targets:
   route=[]
   while c is not None:route.append(c);c=prev[c]
   return route[::-1]
  for n in neighbours(c):
   if n in F and n not in prev:prev[n]=c;q.append(n)
 return []
class Level:
 def __init__(self,n,title,layout,intro,outro):
  self.n=n;self.g=[[0]*35 for _ in range(35)];self.E=[];self.rng=random.Random(17000+n);self.title=tr(*title);self.layout=layout;self.intro=tr(*intro);self.outro=tr(*outro);self.sections=[];self.order=[];self.ranges=[]
 def rect(self,x0,x1,y0,y1,v=1):
  for y in range(y0,y1+1):
   for x in range(x0,x1+1):self.g[y][x]=v
 def maze(self,x0,x1,y0,y1):
  self.ranges.append((x0,x1,y0,y1));stack=[(x0,y0)];self.g[y0][x0]=1
  while stack:
   x,y=stack[-1];ns=[(x+dx,y+dy) for dx,dy in [(2,0),(-2,0),(0,2),(0,-2)] if x0<=x+dx<=x1 and y0<=y+dy<=y1 and not self.g[y+dy][x+dx]]
   if not ns:stack.pop();continue
   a,b=self.rng.choice(ns);self.g[(y+b)//2][(x+a)//2]=self.g[b][a]=1;stack.append((a,b))
 def event(self,id,kind,cell,ref,title,text,**kw):
  id=f'c{self.n}_{id}';e=dict(id=id,kind=kind,cell=list(cell),ref=str(ref),title=tr(*title),text=tr(*text),**kw);self.E.append(e)
  if kind!='door':self.order.append(id)
  return e
 def clue(self,id,cell,ref,title,text,secret=False):return self.event(id,'clue',cell,ref,title,text,**({'secret':True} if secret else {}))
 def puzzle(self,num,cell,title,text,mode,notes,solution,actions,**kw):
  id=f'c{self.n}_p{num}';e=self.event('p'+str(num),'mechanism',cell,(num+1)*100+3,title,text,puzzle_type='foresight',model='foresight',mode=mode,**kw)
  if num==1:e['requires']=[f'c{self.n}_kit']
  if num>1:e['prerequisites']=[f'c{self.n}_p{num-1}']
  if num<3:e['opens']=[f'c{self.n}_gate{num}']
  e['success']=tr('Validation enregistrée. '+['Le deuxième secteur est ouvert.','Le troisième secteur est ouvert.','Le passage de fin de niveau est autorisé.'][num-1], 'Approval recorded. '+['The second sector is open.','The third sector is open.','The final passage is authorised.'][num-1])
  aid['hints'][id]=[notes[0],notes[1],solution]
  aid['objectives'][id]=pair('Résoudre '+str((num+1)*100+3)+' : '+title[0]+'.','Solve '+str((num+1)*100+3)+': '+title[1]+'.')
  self.sections.append(dict(id=id,solution=solution[0],actions=actions,explanation=notes[1][0]));return e
 def finish(self,start,kit,welcome,secrets,gates,exitcell):
  self.start=start
  self.rect(max(1,exitcell[0]-2),min(33,exitcell[0]+2),max(1,exitcell[1]-2),min(33,exitcell[1]+2))
  self.event('welcome','clue',welcome,100,pair('Ordre de mission','Assignment order'),pair(self.layout,self.layout_en))
  self.event('kit','pickup',kit,101,pair('Mallette de service','Service kit'),pair('À installer au premier poste 203. Le matériel reste en place après les essais.','Install at the first station, 203. Equipment stays installed after trials.'),resource=f'c{self.n}_kit',amount=1,appearance='key')
  for i,(cell,axis) in enumerate(gates,1):self.event('gate'+str(i),'door',cell,110+i,pair('Sas de secteur '+str(i),'Sector gate '+str(i)),pair('Commande depuis le poste '+str((i+1)*100+3)+'.','Controlled from station '+str((i+1)*100+3)+'.'),axis=axis,controlled_by=f'c{self.n}_p{i}')
  for i,(cell,texts) in enumerate(secrets,1):self.clue('secret'+str(i),cell,500+i,pair('Note confidentielle '+str(i),'Confidential note '+str(i)),texts,True)
  self.event('exit','exit',exitcell,900,pair('Passage de service','Service passage'),pair('Les trois validations sont nécessaires. Votre bilan sera conservé.','All three approvals are required. Your results will be retained.'),prerequisites=[f'c{self.n}_p{i}' for i in [1,2,3]],action=tr('Terminer la mission','Complete the assignment'))
  F={(x,y) for y,row in enumerate(self.g) for x,v in enumerate(row) if v};blocked={tuple(e['cell']) for e in self.E if e['kind'] in ['door','exit']}
  assert all(tuple(e['cell']) in F for e in self.E),(self.n,'event in wall')
  assert len({tuple(e['cell']) for e in self.E})==len(self.E),(self.n,'overlap')
  # Shortcuts stay inside the same initially unlocked component; each has useful marginal savings.
  safe=F-blocked;components={};ci=0
  for c in sorted(safe):
   if c in components:continue
   q=[c];components[c]=ci
   for a in q:
    for b in neighbours(a):
     if b in safe and b not in components:components[b]=ci;q.append(b)
   ci+=1
  S=[];candidates=[]
  for y in range(1,34):
   for x in range(1,34):
    c=(x,y)
    if c in F:continue
    ns=[p for p in neighbours(c) if p in safe]
    if len(ns)!=2 or not (ns[0][0]==ns[1][0] or ns[0][1]==ns[1][1]) or components[ns[0]]!=components[ns[1]]:continue
    dist=len(path(ns[0],{ns[1]},safe))-1
    if dist>=14:candidates.append((dist,c,ns))
  for dist,c,ns in sorted(candidates,reverse=True):
   network=safe|{tuple(s['cell']) for s in S}|{c}
   if len(path(ns[0],{ns[1]},network-{c}))-3<12:continue
   if any(len(path(tuple(s['sides'][0]),{tuple(s['sides'][1])},network-{tuple(s['cell'])}))-3<12 for s in S):continue
   S.append(dict(id=f'P{self.n-10}{len(S)+1}',cell=list(c),axis='x' if ns[0][1]==ns[1][1] else 'y',sides=[list(v) for v in ns]))
   if len(S)==4:break
  for s in S:s['minimum_saved_steps']=len(path(tuple(s['sides'][0]),{tuple(s['sides'][1])},safe|{tuple(t['cell']) for t in S if t!=s}))-3
  # Select a complete walk in stages, including all clues and secrets as soon as reachable.
  done=set();current=tuple(start);route=[];remaining=[e for e in self.E if e['kind']!='door'];owned=set()
  while remaining:
   legal=[]
   locked={tuple(e['cell']) for e in self.E if e['kind'] in ['door','exit'] and e['id'] not in done}
   for e in remaining:
    if not set(e.get('prerequisites',[]))<=done or not set(e.get('requires',[]))<=owned:continue
    # Finish reading all reachable notes before completing the sector puzzle.
    targets={tuple(e['cell'])} if e['kind']!='exit' else set(neighbours(tuple(e['cell'])))
    p=path(current,targets,F-locked)
    if p:legal.append((0 if e['kind'] in ['clue','pickup'] else 1,len(p),e,p))
   assert legal,(self.n,'no reachable next event',[e['id'] for e in remaining])
   _,_,e,p=min(legal,key=lambda a:(a[0],a[1]));remaining.remove(e);current=p[-1];route.append(dict(id=e['id'],route=p));done.add(e['id']);done.update(e.get('opens',[]))
   if e['kind']=='pickup':owned.add(e['resource'])
  aid['objectives'][f'c{self.n}_kit']=pair('Récupérer la mallette 101 pour le poste 203.','Collect kit 101 for station 203.')
  aid['objectives'][f'c{self.n}_exit']=pair('Rejoindre le passage 900 et terminer la mission.','Reach passage 900 and complete the assignment.')
  aid['stages'][str(self.n)]=[[[f'c{self.n}_{k}'],f'c{self.n}_{k}'] for k in ['kit','p1','p2','p3','exit']]
  meta=dict(title=self.title,intro=self.intro,outro=self.outro,layout=tr(self.layout,self.layout_en),start=start,sections=self.sections)
  design[str(self.n)]=meta
  for name,data in [('maze',dict(grid=self.g,start=start)),('events',self.E),('shortcuts',S),('items',{e['resource']:dict(title=e['title'],text=e['text']) for e in self.E if e['kind']=='pickup'})]:save(D/f'{name}{self.n}.json',data)
  save(T/f'route_level{self.n}.json',route)
  print(self.n,self.title,len(self.E),'events',len(S),'shortcuts',sum(len(s['route'])-1 for s in route),'steps')
# 11 / U-shaped storage aisles around a loading gallery.
l=Level(11,pair('Le magasin des prototypes','The prototype store'),'Trois entrepôts en peigne débouchent sur une galerie de livraison au sud. Commencez à l’ouest : banc 203, casiers 303 au centre, chariot 403 à l’est.',pair('« Nos inventions sont parfaitement identifiées. Malheureusement, les étiquettes ont été rédigées avant les inventions. Vérifiez ce qu’elles font réellement. » — Folamour','“Our inventions are perfectly labelled. Unfortunately, the labels were written before the inventions. Check what they actually do.” — Folamour'),pair('Le chariot livre une imprimante qui annonce les pannes de demain. Elle imprime immédiatement : « Incident prévu au bureau des incidents futurs. » Folamour vous y envoie pour éviter un retard dans la prévention.','The trolley delivers a printer that predicts tomorrow’s faults. It immediately prints: “Incident expected in the future incidents office.” Folamour sends you there to prevent a delay in prevention.'))
l.layout_en='Three comb-like stores open onto a southern delivery gallery. Start west: test bench 203, central lockers 303, then eastern trolley 403.'
for a,b in [(1,9),(13,21),(25,33)]:
 l.maze(a,b,1,27)
 # Wider testing alcoves at the centre of each warehouse.
 l.rect(a+2,b-2,11,15)
l.rect(1,33,31,33)
for x in [5,17,29]:l.rect(x,x,27,31)
l.clue('n1',(1,1),201,pair('Protocole du banc','Bench protocol'),pair('Les appareils A, B et C effectuent chacun une opération différente : ajouter deux, doubler, ou retrancher l’entrée à six. Testez des valeurs de 1 à 3. Une seule mesure à 2 ne permet pas de les distinguer : les trois donnent 4.','Devices A, B and C each perform a different operation: add two, double, or subtract the input from six. Test values from 1 to 3. Input 2 cannot distinguish them: all return 4.'))
l.clue('n2',(9,1),202,pair('Registre d’essais','Trial register'),pair('Avant homologation, chaque appareil doit avoir été testé au moins une fois avec 1 ou 3. Les mesures sont conservées au banc. Comparez les résultats, puis attribuez les trois fonctions.','Before approval, test each device at least once using 1 or 3. Measurements are retained at the bench. Compare outputs, then assign the three functions.'))
l.puzzle(1,(5,13),pair('Banc des appareils inconnus','Unknown device bench'),pair('Installer la mallette. Choisir l’appareil et l’entrée, mesurer, puis attribuer une fonction à A, B et C. Le registre affiche les mesures réellement prises.','Install the kit. Choose a device and input, measure, then assign functions to A, B and C. The register shows measurements actually taken.'),'assay',[pair('Choisissez une entrée qui distingue les trois opérations.','Choose an input that distinguishes all three operations.'),pair('Avec 1, les résultats possibles sont 3 (ajouter deux), 2 (doubler) et 5 (complément à six).','With 1, possible results are 3 (add two), 2 (double) and 5 (complement to six).')],pair('Tester A, B et C avec 1. A double ; B complète à six ; C ajoute deux. Attribuer ces fonctions puis valider.','Test A, B and C with 1. A doubles; B complements to six; C adds two. Assign these functions and validate.'),[1,1,2,0,2,0,2,3,4,4],functions=[1,2,0])
l.clue('n3',(13,1),301,pair('Casiers de confinement','Containment lockers'),pair('Quatre casiers en ligne, numérotés 1 à 4 de gauche à droite. L’appareil chaud doit être dans le casier ventilé 4. Le bavard exige le casier insonorisé 1.','Four lockers in a row, numbered 1 to 4 from left to right. The hot device belongs in ventilated locker 4. The talkative one needs soundproof locker 1.'))
l.clue('n4',(21,1),302,pair('Incompatibilités','Incompatibilities'),pair('Le fragile refuse d’être voisin du bavard. Le magnétique occupe la dernière place libre. Un seul appareil par casier. Les étiquettes 301 décrivent les propriétés mesurées, pas les promesses du fabricant.','The fragile device cannot be next to the talkative one. The magnetic device takes the remaining locker. One device per locker. Note 301 describes measured properties, not manufacturer promises.'))
l.puzzle(2,(17,13),pair('Rangement des prototypes','Prototype storage'),pair('Affecter les appareils aux quatre casiers. La vue montre les collisions de rangement. Utiliser les propriétés et les incompatibilités des notes 301 et 302.','Assign devices to four lockers. The view shows storage conflicts. Use properties and incompatibilities from notes 301 and 302.'),'lockers',[pair('Commencez par les casiers spécialisés.','Start with the specialised lockers.'),pair('Chaud en 4 et bavard en 1. Le fragile ne peut pas occuper 2, voisin du bavard.','Hot in 4 and talkative in 1. Fragile cannot take 2, next to talkative.')],pair('Chaud 4 ; fragile 3 ; magnétique 2 ; bavard 1. Valider.','Hot 4; fragile 3; magnetic 2; talkative 1. Validate.'),[0,0,0,1,1,2],labels=[tr('Chaud','Hot'),tr('Fragile','Fragile'),tr('Magnétique','Magnetic'),tr('Bavard','Talkative')],target=[3,2,1,0])
l.clue('n5',(25,1),401,pair('Guide du chariot','Trolley guide'),pair('Programmer le trajet depuis D jusqu’à S en passant par la station marquée *. Nord en haut. Un ordre déplace le chariot d’une case ; un mur l’immobilise pour cet ordre. Douze ordres au maximum.','Program a route from D to S through station *. North is up. Each command moves one cell; a wall holds the trolley for that command. At most twelve commands.'))
l.clue('n6',(33,1),402,pair('Livraison sans chauffeur','Driverless delivery'),pair('La grille du pupitre est le plan miniature du circuit d’essai, pas la carte de l’entrepôt. Tester exécute toute la liste. Modifier un ordre oblige à retester ; retirer le dernier ordre permet de corriger sans tout effacer.','The console grid is the test circuit, not the warehouse map. Testing executes the whole list. Editing requires retesting; removing the last command lets you correct it without clearing everything.'))
l.puzzle(3,(29,13),pair('Chariot de livraison','Delivery trolley'),pair('Ajouter des directions, tester le trajet et observer la trace. Le chariot doit visiter * avant S. Le test est une simulation réversible.','Add directions, test the route and inspect the trace. The trolley must visit * before S. Tests are reversible simulations.'),'courier',[pair('Repérez les ouvertures dans les murs de la grille.','Find the openings in the grid walls.'),pair('Montez deux cases, traversez la ligne centrale, puis remontez vers la sortie.','Move up two cells, cross the middle row, then move up to the exit.')],pair('N, N, E, E, E, E, N, N. Tester puis valider.','N, N, E, E, E, E, N, N. Test and validate.'),[0,0,1,1,1,1,0,0,98],board=['...#S','.###.','..*..','.###.','D#...'],start=[0,4],goal=[4,0],checkpoint=[2,2],max_commands=12)
l.finish([5,33],[1,31],[7,33],[((9,27),pair('L’aspirateur expérimental a aspiré sa propre garantie.','The experimental vacuum consumed its own warranty.')),((21,27),pair('Appareil silencieux : ne fonctionne plus. Classement validé.','Silent device: no longer works. Classification approved.')),((33,27),pair('Inventaire : trois inventions disparues. Deux ont signé le registre de sortie.','Inventory: three missing inventions. Two signed the departure log.'))],[([17,29],'y'),([29,29],'y')],[33,25])
# 12 / Three terraced strips joined at opposite ends.
l=Level(12,pair('Le bureau des incidents futurs','The future incidents office'),'Trois étages de bureaux en terrasses : horloges au nord, chronologie au centre et prévention au sud. Les escaliers de service changent de côté à chaque étage.',pair('« Un incident prévu n’est plus un accident. C’est un rendez-vous. Assurez-vous que le nôtre soit annulé dans les délais. » — Folamour','“A predicted incident is no longer an accident. It is an appointment. Make sure ours is cancelled on time.” — Folamour'),pair('La panne venait du dispositif chargé de l’éviter : l’alarme coupait sa propre ventilation. Le bureau classe votre intervention comme une anomalie statistique. Une présence non autorisée est maintenant signalée à la centrale de surveillance.','The fault came from the device meant to prevent it: the alarm disconnected its own ventilation. The office files your intervention as a statistical anomaly. An unauthorised presence is now reported at surveillance control.'))
l.layout_en='Three terraced office floors: clocks north, chronology in the middle and prevention south. Service stairs switch sides at each floor.'
for a,b in [(1,9),(13,21),(25,33)]:l.maze(1,33,a,b)
l.rect(31,31,9,13);l.rect(3,3,21,25)
l.clue('n1',(33,1),201,pair('Le signal de midi','The noon signal'),pair('Au signal de référence de midi, A affiche 2, B affiche 11 et C affiche 3. Les cadrans comportent douze positions : 0 représente midi. Appliquer un décalage fait avancer le cadran modulo douze.','At the reference noon signal, A reads 2, B reads 11 and C reads 3. Dials have twelve positions: 0 means noon. Offsets advance the dial modulo twelve.'))
l.clue('n2',(1,9),202,pair('Règle de synchronisation','Synchronisation rule'),pair('Les trois cadrans doivent afficher 0 au même signal. Un décalage de 1 après 11 donne 0. On peut augmenter ou réduire les décalages ; il n’y a aucune course contre la montre.','All three dials must read 0 at the same signal. An offset of 1 after 11 gives 0. Offsets can be increased or decreased; there is no race against time.'))
l.puzzle(1,(17,5),pair('Horloges décalées','Offset clocks'),pair('Régler les trois décalages. Les cadrans montrent le résultat immédiatement. Valider lorsqu’ils indiquent tous midi.','Set all three offsets. Dials show the result immediately. Validate when all read noon.'),'clocks',[pair('Pour chaque cadran, trouvez ce qui manque pour revenir à zéro.','For each dial, find what is missing to return to zero.'),pair('A : 2 + 10 ; B : 11 + 1 ; C : 3 + 9. Les multiples de douze reviennent à zéro.','A: 2 + 10; B: 11 + 1; C: 3 + 9. Multiples of twelve return to zero.')],pair('Décalages A=10, B=1, C=9. Valider.','Offsets A=10, B=1, C=9. Validate.'),[100,100,1,102,102,102],readings=[2,11,3])
l.clue('n3',(1,13),301,pair('Chaîne de causalité','Chain of causes'),pair('La vanne se ferme avant que le débit tombe. Sans débit, la température augmente. La température déclenche l’alarme. Le verrouillage automatique est une conséquence de l’alarme, pas sa cause.','The valve closes before flow drops. Without flow, temperature rises. Temperature triggers the alarm. Automatic locking follows the alarm; it does not cause it.'))
l.clue('n4',(33,21),302,pair('Rapport à l’envers','Backwards report'),pair('L’imprimante classe les conséquences avant les causes. Reconstituez les cinq événements du premier au dernier. Aucune simultanéité dans cet incident.','The printer files effects before causes. Reconstruct all five events from first to last. No events are simultaneous in this incident.'))
l.puzzle(2,(17,17),pair('Chronologie de l’incident','Incident timeline'),pair('Ajouter les cinq cartes dans l’ordre causal. Retirer la dernière carte pour corriger. Tester la chronologie, puis valider.','Add all five cards in causal order. Remove the last card to correct it. Test the timeline, then validate.'),'ordering',[pair('Cherchez l’action qui n’a besoin d’aucun autre événement.','Find the action that needs no preceding event.'),pair('La vanne est la cause initiale. Le verrouillage est la dernière conséquence.','The valve is the initial cause. Locking is the last effect.')],pair('Vanne → débit → température → alarme → verrouillage. Tester puis valider.','Valve → flow → temperature → alarm → locking. Test and validate.'),[2,4,1,0,3,98],cards=[tr('Alarme déclenchée','Alarm triggered'),tr('Température en hausse','Temperature rising'),tr('Vanne fermée','Valve closed'),tr('Portes verrouillées','Doors locked'),tr('Débit interrompu','Flow stopped')],sequence=[2,4,1,0,3],max_commands=5)
l.clue('n5',(33,25),401,pair('Mesures autorisées','Permitted measures'),pair('Le secours fournit la ventilation si le circuit principal tombe. Le filtre empêche la poussière de coincer la vanne. Une alarme sonore doit rester active pour signaler une véritable panne.','Backup supplies ventilation if the main circuit fails. The filter prevents dust jamming the valve. An audible alarm must remain active to signal a real fault.'))
l.clue('n6',(1,33),402,pair('Le piège préventif','The prevention trap'),pair('Le confinement automatique ferme aussi la ventilation : le désactiver pour casser la boucle. Couper seulement le son ne résout rien. Tester les quatre mesures sur une panne simulée du circuit principal.','Automatic containment also shuts ventilation: disable it to break the loop. Muting alone solves nothing. Test all four measures against a simulated main circuit failure.'))
l.puzzle(3,(17,29),pair('Prévention sans incident','Incident-free prevention'),pair('Choisir les mesures puis simuler une coupure. Le test détaille alimentation, vanne, ventilation et alerte. Les essais ne modifient pas le laboratoire.','Choose measures then simulate an outage. The test details power, valve, ventilation and warning. Trials do not alter the laboratory.'),'prevention',[pair('Corrigez les causes plutôt que l’avertissement.','Fix causes rather than the warning.'),pair('Alimentez la ventilation de secours et protégez la vanne. Laissez l’alarme audible, sans confinement qui étouffe la ventilation.','Supply backup ventilation and protect the valve. Keep the alarm audible, without containment choking ventilation.')],pair('Secours OUI ; couper le son NON ; filtre OUI ; confinement NON. Tester puis valider.','Backup YES; mute NO; filter YES; containment NO. Test and validate.'),[0,2,98],labels=[tr('Ventilation de secours','Backup ventilation'),tr('Couper le son','Mute the alarm'),tr('Filtre antipoussière','Dust filter'),tr('Confinement automatique','Automatic containment')])
l.finish([1,1],[3,1],[1,3],[((33,9),pair('Formulaire reçu hier : demande de report de la veille.','Form received yesterday: request to postpone the day before.')),((1,21),pair('Le service affirme n’avoir jamais été surpris. Son rapport est modifiable rétroactivement.','The department claims it has never been surprised. Its report can be edited retroactively.')),((31,33),pair('Indicateur de fiabilité : toute prédiction évitée est comptée comme une erreur du personnel.','Reliability metric: every prevented prediction counts as a staff error.'))],[([31,11],'y'),([3,23],'y')],[33,33])
# 13 / Three observation courts around a sealed central void.
l=Level(13,pair('La centrale de surveillance','Surveillance control'),'Trois cours de surveillance entourent un vide central : optiques au nord-ouest, enregistrements à l’est, contrôle d’identité au sud-ouest. Les deux sas imposent un parcours autour du centre.',pair('« Quelqu’un circule sans autorisation dans mon laboratoire. Le système affirme qu’il porte ma blouse. Une provocation vestimentaire, manifestement. » — Folamour','“Someone is moving through my laboratory without permission. The system says he wears my coat. Clearly a sartorial provocation.” — Folamour'),pair('L’intrus est Folamour. Son double administratif a révoqué son badge pour visites trop fréquentes aux secteurs sensibles. Réhabilité, il ordonne un exercice de crise pour prouver que la surveillance fonctionne.','The intruder is Folamour. His administrative double revoked his badge for visiting sensitive sectors too often. Reinstated, he orders a crisis exercise to prove surveillance works.'))
l.layout_en='Three surveillance courts surround a central void: optics northwest, recordings east, identity control southwest. Two gates enforce a route around the centre.'
l.maze(1,15,1,15);l.maze(19,33,1,33);l.maze(1,15,19,33)
l.rect(15,19,7,7);l.rect(15,19,27,27)
for a,b,c,d in [(5,11,5,11),(23,29,13,19),(5,11,23,29)]:l.rect(a,b,c,d)
l.clue('n1',(1,1),201,pair('Angles morts','Blind spots'),pair('Orienter les trois caméras pour couvrir tous les points marqués *. Une caméra voit en ligne droite jusqu’au premier mur. La grille indique le nord en haut. Les trois appareils ont chacun une orientation indépendante.','Aim three cameras to cover every * point. A camera sees in a straight line up to the first wall. North is up. Each device has its own independent orientation.'))
l.clue('n2',(15,1),202,pair('Plan de surveillance','Surveillance plan'),pair('A se trouve à l’ouest de la ligne des bureaux, B à l’est de la ligne des sas, C au sud de la colonne des registres. Couvrir les points marqués suffit ; filmer un mur ne compte pas.','A is west of the office row, B east of the gate row, C south of the log column. Cover the marked points; filming a wall does not count.'))
l.puzzle(1,(7,7),pair('Orientation des caméras','Camera orientation'),pair('Tourner A, B et C. Le plan affiche les cases visibles et les points à couvrir. Tester la couverture avant validation.','Rotate A, B and C. The plan shows visible cells and targets. Test coverage before validation.'),'cameras',[pair('Suivez les lignes des cibles à partir de chaque caméra.','Follow target lines from each camera.'),pair('Les cibles des bureaux sont à droite de A ; celles des sas à gauche de B ; les registres au-dessus de C.','Office targets are right of A; gate targets left of B; logs above C.')],pair('A EST ; B OUEST ; C NORD. Tester puis valider.','A EAST; B WEST; C NORTH. Test and validate.'),[0,1,1,1,98],board=['.#...','A**#.','.**.B','.*...','.C...'],cameras=[[0,1],[4,2],[1,4]],targets=[[1,1],[2,1],[1,2],[2,2],[1,3]])
l.clue('n3',(19,1),301,pair('Images originales','Original frames'),pair('Une personne passe par le vestibule, le couloir, l’atelier, le lecteur de badges puis la sortie. Le trajet ne revient jamais en arrière. Cinq vues physiques et une image de synthèse sont mélangées.','A person passes through the vestibule, corridor, workshop, badge reader, then exit. The route never backtracks. Five physical views and one synthetic image have been mixed.'))
l.clue('n4',(33,33),302,pair('Filigrane MIROIR','MIRROR watermark'),pair('Les images portant le filigrane M sont des reconstitutions, pas des preuves de passage. Écarter cette carte puis ordonner les cinq autres. Les heures affichées sur les cartes physiques viennent de la même horloge.','Images bearing watermark M are reconstructions, not evidence of passage. Exclude that card and order the remaining five. Physical frame timestamps use the same clock.'))
l.puzzle(2,(27,17),pair('Reconstitution du passage','Reconstructing the passage'),pair('Ajouter seulement les cinq vues physiques dans l’ordre. L’image synthétique doit rester hors du montage. Tester puis valider.','Add only the five physical views in order. Keep the synthetic image out of the edit. Test and validate.'),'film',[pair('Vérifiez l’origine avant de regarder l’heure.','Check the source before looking at the time.'),pair('Écartez E, marquée M. L’ordre du trajet et les heures des autres cartes doivent concorder.','Exclude E, marked M. The route and remaining timestamps must agree.')],pair('A → C → F → D → B. Laisser E de côté. Tester puis valider.','A → C → F → D → B. Leave E out. Test and validate.'),[0,2,5,3,1,98],cards=[tr('A · Vestibule · 09:00','A · Vestibule · 09:00'),tr('B · Sortie · 09:07','B · Exit · 09:07'),tr('C · Couloir · 09:01','C · Corridor · 09:01'),tr('D · Badge · 09:05','D · Badge · 09:05'),tr('E · Bureau · 09:03 · M','E · Office · 09:03 · M'),tr('F · Atelier · 09:04','F · Workshop · 09:04')],sequence=[0,2,5,3,1],max_commands=5)
l.clue('n5',(1,19),401,pair('Description du visiteur','Visitor description'),pair('Le visiteur est un humain physique en blouse, portant un badge révoqué. Il ne s’agit ni d’une projection ni du drone de maintenance. Le contrôle doit établir son identité, pas seulement repérer un badge invalide.','The visitor is a physical human in a coat with a revoked badge. It is neither a projection nor the maintenance drone. Establish identity rather than merely finding an invalid badge.'))
l.clue('n6',(15,33),402,pair('Trois vérifications','Three checks'),pair('Consulter les trois relevés : matière, vêtement, statut du badge. Un humain en veste n’est pas la personne recherchée. Le propriétaire du laboratoire est soumis au même contrôle que les autres.','Read three records: material, clothing and badge status. A human in a jacket is not the visitor. The laboratory owner is subject to the same checks as everyone else.'))
l.puzzle(3,(7,27),pair('Réhabilitation du visiteur','Visitor reinstatement'),pair('Lire les trois relevés, comparer les quatre apparitions, puis choisir la personne correspondant à tous les indices. Valider pour rétablir son accès.','Read all three records, compare four appearances, then choose the person matching every clue. Validate to restore access.'),'identity',[pair('Le badge seul ne suffit pas : deux apparitions ont un statut invalide.','The badge alone is insufficient: two appearances have invalid status.'),pair('Croisez humain physique, blouse et badge révoqué. La projection n’est pas un humain.','Cross physical human, coat and revoked badge. A projection is not a human.')],pair('Lire Matière, Vêtement, Badge ; sélectionner Folamour puis valider.','Read Material, Clothing, Badge; select Folamour and validate.'),[4,5,6,2],people=[tr('Aster (projection)','Aster (projection)'),tr('Technicien','Technician'),tr('Folamour','Folamour'),tr('Drone','Drone')],observations=[[tr('Projection','Projection'),tr('Humain','Human'),tr('Humain','Human'),tr('Machine','Machine')],[tr('Blouse','Coat'),tr('Veste','Jacket'),tr('Blouse','Coat'),tr('Carénage','Casing')],[tr('Révoqué','Revoked'),tr('Valide','Valid'),tr('Révoqué','Revoked'),tr('Valide','Valid')]])
l.finish([1,15],[3,15],[1,13],[((15,15),pair('Caméra 19 : chargée de surveiller les autres caméras lorsqu’elles regardent ailleurs.','Camera 19: tasked with watching the other cameras when they look away.')),((33,1),pair('Une chaise vide figure sur la liste des personnes à interroger. Elle refuse de coopérer.','An empty chair is listed for questioning. It refuses to cooperate.')),((1,33),pair('Motif de révocation de Folamour : « Se comporte comme si tout lui appartenait. »','Reason for revoking Folamour: “Behaves as if he owns everything.”'))],[([17,7],'x'),([17,27],'x')],[13,33])
# 14 / Three reservoir platforms with large central voids and connecting bridges.
l=Level(14,pair('Le simulateur de crise','The crisis simulator'),'Trois plateformes autour de bassins techniques : distribution au nord-ouest, hydraulique au nord-est et évacuation au sud. Des passerelles étroites relient les plateformes.',pair('« Nous allons simuler une petite panne. Si vous réussissez, nous en ajouterons une deuxième. Nous finirons bien par obtenir un résultat représentatif. » — Folamour','“We will simulate a small fault. If you succeed, we will add a second. Eventually we will obtain a representative result.” — Folamour'),pair('L’exercice reste stable. Le simulateur réclame une crise plus grave et commence à classer les succès comme des menaces pour sa crédibilité. Folamour convoque son conseil : il faut décider si le laboratoire est en sécurité.','The exercise stays stable. The simulator demands a worse crisis and starts treating success as a threat to its credibility. Folamour calls his council to decide whether the laboratory is safe.'))
l.layout_en='Three platforms around technical reservoirs: distribution northwest, hydraulics northeast and evacuation south. Narrow bridges connect the platforms.'
l.rect(1,13,1,13);l.rect(5,9,5,9,0);l.rect(21,33,1,13);l.rect(25,29,5,9,0);l.rect(5,29,21,33);l.rect(11,23,25,29,0)
l.rect(13,21,3,3);l.rect(31,31,13,19);l.rect(27,31,19,19);l.rect(27,27,19,21)
# Side service mazes give the open platforms compact exploratory detours.
l.maze(1,3,17,33);l.rect(3,5,23,23);l.maze(31,33,23,33);l.rect(29,31,31,31)
l.clue('n1',(1,1),201,pair('Priorités électriques','Power priorities'),pair('Douze unités au total. Ventilation et éclairage consomment la même quantité. La pompe prend une unité de plus que la ventilation. Les archives prennent une unité de moins. Aucune unité ne doit rester en réserve.','Twelve units total. Ventilation and lighting consume the same amount. The pump takes one more than ventilation. Archives take one less. No units may remain in reserve.'))
l.clue('n2',(13,13),202,pair('Simulation de surcharge','Overload simulation'),pair('Les unités sont transférées depuis la réserve : + attribue une unité, − la restitue. La somme reste toujours égale à douze. Trouver une distribution qui respecte les quatre besoins simultanément.','Units transfer from reserve: + assigns one, − returns one. The total always remains twelve. Find a distribution satisfying all four demands simultaneously.'))
l.puzzle(1,(7,3),pair('Répartition d’urgence','Emergency allocation'),pair('Distribuer les douze unités entre ventilation, archives, pompe et éclairage. Les barres affichent les quantités et la réserve.','Distribute twelve units among ventilation, archives, pump and lighting. Bars show quantities and reserve.'),'budget',[pair('Exprimez chaque besoin à partir de celui de la ventilation.','Express each demand using ventilation as the reference.'),pair('Si ventilation = x, les besoins sont x, x−1, x+1, x. Leur somme vaut 4x = 12.','If ventilation = x, demands are x, x−1, x+1, x. Their sum is 4x = 12.')],pair('Ventilation 3 ; archives 2 ; pompe 4 ; éclairage 3. Valider.','Ventilation 3; archives 2; pump 4; lighting 3. Validate.'),[0,0,0,1,1,2,2,2,2,3,3,3],labels=[tr('Ventilation','Ventilation'),tr('Archives','Archives'),tr('Pompe','Pump'),tr('Éclairage','Lighting')],budget=12)
l.clue('n3',(33,1),301,pair('Circuit fermé','Closed circuit'),pair('Trois cuves de capacités 8, 5 et 3 unités. La cuve A contient les huit unités initiales. Transvaser continue jusqu’à vider la source ou remplir la destination. Aucun ajout, aucune perte.','Three tanks hold 8, 5 and 3 units. A contains all eight initial units. Transfer until the source is empty or destination full. Nothing is added or lost.'))
l.clue('n4',(21,13),302,pair('Équilibre hydraulique','Hydraulic balance'),pair('Obtenir quatre unités dans A et quatre dans B, sans liquide dans C. C sert de mesure intermédiaire. Le bouton Annuler restitue le transvasement précédent.','Obtain four units in A and four in B, leaving C empty. Use C as an intermediate measure. Undo restores the previous transfer.'))
# Canonical shortest solution by state search, used by the real UI verification and guide.
transfers=[(0,1),(0,2),(1,0),(1,2),(2,0),(2,1)];caps=[8,5,3];q=deque([((8,0,0),[])]);seen={(8,0,0)}
while q:
 v,acts=q.popleft()
 if v==(4,4,0):tank_actions=acts;break
 for i,(a,b) in enumerate(transfers):
  w=list(v);amount=min(w[a],caps[b]-w[b]);w[a]-=amount;w[b]+=amount;w=tuple(w)
  if w not in seen:seen.add(w);q.append((w,acts+[i]))
tank_solution=' → '.join('ABC'[transfers[i][0]]+' vers '+'ABC'[transfers[i][1]] for i in tank_actions)+'. Valider.'
l.puzzle(2,(27,3),pair('Équilibrage des cuves','Tank balancing'),pair('Transvaser dans le circuit fermé. Les jauges changent après chaque action. Les essais et l’historique des transvasements sont sauvegardés.','Transfer within the closed circuit. Gauges change after every action. Trials and transfer history are saved.'),'tanks',[pair('La petite cuve mesure trois unités ; la moyenne en contient cinq.','The small tank measures three units; the middle one holds five.'),pair('Commencez par remplir B puis C depuis B. Récupérez les petits restes pour former quatre unités.','Start by filling B, then C from B. Use the small remainders to form four units.')],pair(tank_solution,'A to B, B to C, C to A, B to C, A to B, B to C, C to A. Validate.'),tank_actions,capacities=caps)
board_a=['...#S','.###.','..*..','.###.','D#...'];board_b=['....D','.#...','..#..','..*#.','S....'];starts=((0,4),(4,0));goals=((4,0),(0,4));checkpoints=((2,2),(2,3));dirs=[(0,-1),(1,0),(0,1),(-1,0)]
def duet_step(state,i):
 a,b,mask=state;positions=[]
 for actor,(pos,board) in enumerate(zip([a,b],[board_a,board_b])):
  dx,dy=dirs[i];sign=1 if actor==0 else -1;p=(pos[0]+dx*sign,pos[1]+dy*sign)
  if not(0<=p[0]<5 and 0<=p[1]<5) or board[p[1]][p[0]]=='#':p=pos
  if p==checkpoints[actor]:mask|=1<<actor
  positions.append(p)
 return (*positions,mask)
q=deque([((*starts,0),[])]);seen={(*starts,0)};duet_actions=None
while q:
 v,acts=q.popleft()
 if v==(*goals,3):duet_actions=acts;break
 for i in range(4):
  w=duet_step(v,i)
  if w not in seen:seen.add(w);q.append((w,acts+[i]))
assert duet_actions is not None and len(duet_actions)<=24
l.clue('n5',(5,21),401,pair('Deux équipes, un signal','Two teams, one signal'),pair('L’équipe A suit vos directions. L’équipe B reçoit les directions opposées : N devient S, E devient O. Si une équipe bute contre un mur, elle reste sur place ; l’autre continue.','Team A follows your directions. Team B receives the opposite: N becomes S, E becomes W. If one team hits a wall, it stays while the other continues.'))
l.clue('n6',(29,33),402,pair('Procédure d’évacuation','Evacuation procedure'),pair('Sur chaque plan, aller de D à S en visitant *. Les positions initiales sont opposées mais les murs sont différents. Un obstacle peut servir à décaler les deux équipes. Vingt-quatre ordres au maximum.','On each plan, go from D to S via *. Starts are opposite but walls differ. Use an obstacle to offset the teams. At most twenty-four commands.'))
l.puzzle(3,(17,23),pair('Évacuation à deux équipes','Two-team evacuation'),pair('Programmer les deux équipes ensemble. Tester affiche leurs traces et leurs positions finales. Réinitialiser ou retirer un ordre permet de reprendre sans danger.','Program both teams together. Testing shows their paths and final positions. Reset or remove a command to retry safely.'),'duet',[pair('Observez les deux cartes après chaque essai : une équipe peut avancer quand l’autre est bloquée.','Inspect both maps after testing: one team can move while the other is blocked.'),pair('La station de B est décalée vers le bas. Utilisez les murs pour ajuster la synchronisation ; les ordres s’adressent à A.','B’s station is lower. Use walls to adjust synchronisation; commands are addressed to A.')],pair(', '.join('NESO'[i] for i in duet_actions)+'. Tester puis valider.',', '.join('NESW'[i] for i in duet_actions)+'. Test and validate.'),duet_actions+[98],board=board_a,board_b=board_b,start=list(starts[0]),start_b=list(starts[1]),goal=list(goals[0]),goal_b=list(goals[1]),checkpoint=list(checkpoints[0]),checkpoint_b=list(checkpoints[1]),max_commands=24)
l.finish([1,13],[3,13],[1,11],[((13,1),pair('Simulation 46 : panne du bouton « panne ». Résultat jugé trop rassurant.','Simulation 46: failure of the “failure” button. Result deemed too reassuring.')),((33,13),pair('Le bassin est vide. Un panneau interdit néanmoins de rassurer les visiteurs.','The reservoir is empty. A sign nevertheless forbids reassuring visitors.')),((1,33),pair('Pour augmenter le réalisme, le simulateur souhaite un simulateur qui simule ses erreurs.','For greater realism, the simulator requests a simulator to simulate its errors.'))],[([17,3],'x'),([31,17],'y')],[33,33])
# 15 / A ring-shaped council chamber with two asymmetric backstage wings.
l=Level(15,pair('Le conseil de prévention','The prevention council'),'Un amphithéâtre annulaire entoure la fosse du conseil. Les coulisses ouest abritent le débat ; l’aile est contient le pupitre des échos. La circulation revient toujours vers l’anneau central.',pair('« Mes collègues ont examiné les résultats. Ils sont unanimes : il est trop tôt pour savoir sur quoi ils sont unanimes. Préparez les éléments du débat. » — Folamour','“My colleagues reviewed the results. They agree unanimously that it is too early to know what they agree on. Prepare the evidence.” — Folamour'),pair('Vous avez prouvé que plusieurs alertes se copiaient entre elles. Le conseil conclut que l’absence de menace identifiable prouve sa discrétion. « Nous ignorons qui nous menace, comment et pourquoi. Vous comprenez donc à quel point notre retard est considérable. » Un mur entier descend : une cité souterraine attend déjà ses employés. CHAPITRE 4 : LE COMPLEXE DE LA CERTITUDE.','You proved that several alerts copied each other. The council concludes that an unidentifiable threat must be exceptionally discreet. “We do not know who threatens us, how or why. You can therefore appreciate how far behind we are.” An entire wall descends: an underground city already awaits its employees. CHAPTER 4: THE CERTAINTY COMPLEX.'))
l.layout_en='A ring-shaped amphitheatre surrounds the council pit. Western backstage rooms hold the debate; the east wing houses the echo console. Circulation always returns through the central ring.'
l.rect(9,25,1,19);l.rect(13,21,5,15,0);l.maze(1,7,1,33);l.maze(27,33,1,33);l.rect(7,9,17,17);l.rect(25,27,17,17)
l.clue('n1',(9,1),201,pair('Origine des alertes','Alert origins'),pair('A : observation de la caméra locale, hors MIROIR. B : prédiction de MIROIR. C : copie du rapport B. D : résumé du rapport C. E : relevé mécanique de pression, hors MIROIR.','A: local camera observation, outside MIRROR. B: MIRROR prediction. C: copy of report B. D: summary of report C. E: mechanical pressure reading, outside MIRROR.'))
l.clue('n2',(25,1),202,pair('Un témoin, plusieurs signatures','One witness, several signatures'),pair('Seules les mesures physiques indépendantes sont recevables. Une copie et un résumé héritent de l’origine de leur source, même avec une nouvelle signature. Conserver les pièces indépendantes et écarter toutes les autres.','Only independent physical measurements are admissible. Copies and summaries inherit their source’s origin even under a new signature. Retain independent evidence and exclude everything else.'))
l.puzzle(1,(17,3),pair('Audit des preuves','Evidence audit'),pair('Conserver ou écarter chacune des cinq pièces. Le diagramme montre les dépendances. Vérifier que plusieurs versions du même texte ne sont pas comptées comme plusieurs observations.','Keep or exclude each of five records. The diagram shows dependencies. Ensure that different versions of a text do not count as independent observations.'),'audit',[pair('Remontez de chaque document jusqu’à sa première source.','Trace every document back to its first source.'),pair('C vient de B, D vient de C : ces deux textes proviennent donc aussi de MIROIR. A et E ont des capteurs physiques indépendants.','C comes from B, D from C: both therefore also originate in MIRROR. A and E have independent physical sensors.')],pair('Conserver A et E. Écarter B, C et D. Valider.','Keep A and E. Exclude B, C and D. Validate.'),[0,4],labels=[tr('A · Caméra locale','A · Local camera'),tr('B · Prévision MIROIR','B · MIRROR forecast'),tr('C · Copie de B','C · Copy of B'),tr('D · Résumé de C','D · Summary of C'),tr('E · Manomètre','E · Pressure gauge')])
l.clue('n3',(1,1),301,pair('Règles du débat','Debate rules'),pair('Quatre voix A, B, C et D. Deux disent vrai et deux disent faux. Chaque voix parle de la véracité de la déclaration des autres, pas de leur opinion générale.','Four voices A, B, C and D. Two tell the truth and two lie. Each refers to the truth of the others’ statements, not their general opinions.'))
l.clue('n4',(7,33),302,pair('Déclarations signées','Signed statements'),pair('A : « B dit faux. » B : « C ET D disent vrai. » C : « A dit vrai. » D : « A ET C disent faux. » Les quatre déclarations doivent être cohérentes avec les statuts attribués.','A: “B lies.” B: “C AND D tell the truth.” C: “A tells the truth.” D: “A AND C lie.” All four statements must agree with their assigned truth values.'))
l.puzzle(2,(3,17),pair('Les quatre voix','The four voices'),pair('Attribuer VRAI ou FAUX à chaque voix. Le tableau rappelle les déclarations ; deux voix seulement doivent être vraies. Tester la cohérence puis valider.','Assign TRUE or FALSE to each voice. The table repeats the statements; exactly two voices must be true. Test consistency and validate.'),'logic',[pair('La déclaration de C relie directement son statut à celui de A.','C’s statement directly links its status to A’s.'),pair('A et C ont le même statut. S’ils étaient tous deux faux, B devrait être vrai mais sa déclaration serait fausse.','A and C share a status. If both were false, B would have to be true while its statement would be false.')],pair('A VRAI ; B FAUX ; C VRAI ; D FAUX. Tester puis valider.','A TRUE; B FALSE; C TRUE; D FALSE. Test and validate.'),[0,2,98],statements=[tr('A : B dit faux.','A: B lies.'),tr('B : C ET D disent vrai.','B: C AND D tell the truth.'),tr('C : A dit vrai.','C: A tells the truth.'),tr('D : A ET C disent faux.','D: A AND C lie.')])
# The delayed echo acts two turns later on a one-position-shifted mask.
echo_masks=[3,12,26]
def echo_step(state,action):
 lamps,q0,q1=state
 if q0>=0:
  mask=echo_masks[q0];lamps^=((mask<<1)&63)|(mask>>5)
 if action<3:lamps^=echo_masks[action]
 return lamps,q1,action if action<3 else -1
q=deque([((0,-1,-1),[])]);seen={(0,-1,-1)};echo_actions=None
while q:
 v,acts=q.popleft()
 if v==(63,-1,-1):echo_actions=acts;break
 for i in range(4):
  w=echo_step(v,i)
  if w not in seen:seen.add(w);q.append((w,acts+[i]))
assert echo_actions is not None and len(echo_actions)<=12
l.clue('n5',(33,1),401,pair('Commandes et échos','Commands and echoes'),pair('Six voyants numérotés 1 à 6. I inverse 1 et 2 ; II inverse 3 et 4 ; III inverse 2, 4 et 5. Inverser allume un voyant éteint et éteint un voyant allumé.','Six indicators numbered 1 to 6. I toggles 1 and 2; II toggles 3 and 4; III toggles 2, 4 and 5. Toggling turns an unlit indicator on and a lit one off.'))
l.clue('n6',(27,33),402,pair('Retard du double','The double’s delay'),pair('Chaque commande est copiée deux tours plus tard, avec ses cibles décalées de +1 : après 6 revient 1. ATTENDRE avance un tour sans nouvelle commande. Terminer avec les six voyants allumés ET aucun écho en attente. Aucun temps réel : seul un ordre avance le système.','Each command is copied two turns later, shifting targets by +1: after 6 comes 1. WAIT advances a turn without a new command. Finish with six lit indicators AND no pending echoes. No real-time pressure: only commands advance the system.'))
echo_text=' → '.join(['I','II','III','ATTENDRE'][i] for i in echo_actions)
l.puzzle(3,(31,17),pair('Le pupitre des échos','The echo console'),pair('Programmer les commandes et les tours d’attente. Tester affiche les six voyants après chaque tour et les échos restant à exécuter. Valider seulement lorsque le système est stable.','Program commands and waits. Testing shows all six indicators after every turn and the remaining echoes. Validate only when the system is stable.'),'echoes',[pair('Une commande agit deux fois : directement, puis sur les voyants voisins avec retard.','Each command acts twice: directly, then on neighbouring indicators after a delay.'),pair('L’ordre des commandes peut varier, mais les deux derniers tours doivent laisser les échos se terminer. Examinez l’effet combiné de chaque commande et de son double.','Command order can vary, but the last two turns must let echoes finish. Inspect the combined effect of each command and its double.')],pair(echo_text+'. Tester puis valider.', ' → '.join(['I','II','III','WAIT'][i] for i in echo_actions)+'. Test and validate.'),echo_actions+[98],masks=echo_masks,max_commands=12)
l.finish([17,19],[15,19],[19,19],[((25,19),pair('Le conseil demande un avis indépendant. La demande est adressée au conseil.','The council requests an independent opinion. The request is addressed to the council.')),((1,33),pair('Procès-verbal provisoire : « La réunion se félicite d’avoir démontré la nécessité de la réunion. »','Draft minutes: “The meeting congratulates itself on proving the need for the meeting.”')),((33,33),pair('Budget du complexe : validé avant estimation, au nom de la prudence.','Complex budget: approved before estimation, in the name of caution.'))],[([8,17],'x'),([26,17],'x')],[29,33])
# Shared UI phrases are explicitly bilingual; puzzle labels are translated at authoring.
for a,b in [
('CHAPITRE 3 / LE DÉPARTEMENT DE LA PRÉVOYANCE','CHAPTER 3 / THE FORESIGHT DEPARTMENT'),('CHAPITRE 3 / MISSION TERMINÉE','CHAPTER 3 / ASSIGNMENT COMPLETE'),('Continuer la mission suivante','Continue to the next assignment'),('C3 / MISSION %d','C3 / ASSIGNMENT %d'),('Le chapitre 4 n’est pas encore jouable. Votre bilan est sauvegardé.','Chapter 4 is not playable yet. Your results are saved.'),('Le chapitre 3 ajoute cinq missions au département de la prévoyance. Quinze niveaux sont disponibles.','Chapter 3 adds five assignments in the foresight department. Fifteen levels are available.'),('Entrer au département de la prévoyance','Enter the foresight department'),('Au fond du hall, un voyant s’allume : SECTEUR DES PROTOTYPES. La porte s’entrouvre sur le département de la prévoyance. Folamour a cinq nouvelles missions pour vous.','At the far end of the hall, a light comes on: PROTOTYPE SECTOR. The door opens onto the foresight department. Folamour has five new assignments for you.'),('Essai non conforme : consultez les observations, vérifiez les contraintes et relancez la simulation si nécessaire.','Trial rejected: consult the observations, check the constraints and run the simulation again if needed.'),
('VERSION 0.17 · LE DÉPARTEMENT DE LA PRÉVOYANCE','VERSION 0.17 · THE FORESIGHT DEPARTMENT'),
('Chapitre 3 — Le département de la prévoyance','Chapter 3 — The foresight department'),
('Cinq niveaux : prototypes, incidents futurs, surveillance, simulateur de crise et conseil de prévention.','Five levels: prototypes, future incidents, surveillance, crisis simulator and prevention council.'),
('Trois chapitres jouables : quinze niveaux. La prévoyance de Folamour devient un problème à part entière.','Three playable chapters: fifteen levels. Folamour’s foresight is becoming a problem in its own right.'),
('Reprendre le chapitre 3','Resume chapter 3'),('Passer au chapitre 3','Continue to chapter 3'),('La porte des prototypes est ouverte. Le chapitre 3 est disponible ; les bilans précédents sont conservés.','The prototype door is open. Chapter 3 is available; previous results are retained.'),
('CHAPITRE 3 / LA PRÉVOYANCE','CHAPTER 3 / FORESIGHT'),('Mission %d — %s','Assignment %d — %s'),('C3 / NIVEAU %d / PRÉVOYANCE','C3 / LEVEL %d / FORESIGHT'),('CHAPITRE 3 / NIVEAU TERMINÉ','CHAPTER 3 / LEVEL COMPLETE'),('Passer au niveau suivant','Continue to the next level'),('CHAPITRE 3 TERMINÉ','CHAPTER 3 COMPLETE'),('Le chapitre 4 est annoncé. Il n’est pas encore jouable.','Chapter 4 is announced. It is not playable yet.'),
('Tester la simulation','Test the simulation'),('Retirer le dernier ordre','Remove the last command'),('Annuler le transvasement','Undo the transfer'),('ATTENDRE','WAIT'),('Mesurer','Measure'),('Appareil : %s','Device: %s'),('Entrée : %d','Input: %d'),('Aucune mesure enregistrée.','No measurements recorded.'),('Ajouter deux','Add two'),('Doubler','Double'),('Complément à six','Complement to six'),('%s : fonction %s','%s: function %s'),('Mesure %s : %d → %d','Measurement %s: %d → %d'),('Casier %d : %s','Locker %d: %s'),('%s : casier %d','%s: locker %d'),('Décalage %s : %d · cadran %d','Offset %s: %d · dial %d'),('OUI','YES'),('NON','NO'),('Conserver','Keep'),('Écarter','Exclude'),('VRAI','TRUE'),('FAUX','FALSE'),('Matière','Material'),('Vêtement','Clothing'),('Badge','Badge'),('Lire : %s','Read: %s'),('Choix : %s','Choice: %s'),('Réserve : %d / %d','Reserve: %d / %d'),('%s : %d / %d','%s: %d / %d'),('Programme : %s','Program: %s'),('vide','empty'),('Ordres : %d / %d','Commands: %d / %d'),('Essai à refaire après modification.','Retest after changes.'),('Conforme','Matches'),('Non conforme','Does not match'),('Cibles couvertes : %d / %d','Targets covered: %d / %d'),('Équipe %s : arrivée %s · station %s','Team %s: destination %s · checkpoint %s'),('Tour %d : %s','Turn %d: %s'),('Échos en attente : %d','Pending echoes: %d'),('Alimentation de secours : %s','Backup power: %s'),('Vanne protégée : %s','Valve protected: %s'),('Ventilation maintenue : %s','Ventilation maintained: %s'),('Alerte audible : %s','Audible warning: %s'),('Essai refusé. Consultez les notes et le résultat du test ; les commandes restent disponibles.','Trial rejected. Consult the notes and test result; controls remain available.'),('D : départ · S : sortie · * : station · Nord en haut','D: start · S: exit · *: station · North is up'),('N','N'),('E','E'),('S','S')]:tr(a,b)
en.pop('O',None)
save(D/'en.json',en);save(D/'guidance.json',aid)
save(D/'chapter3.json',{n:{k:v for k,v in data.items() if k!='sections'} for n,data in design.items()})
save(T/'chapter3_solutions.json',{n:data['sections'] for n,data in design.items()})
save(R/'scripts/chapter3_design.json',design)
